import colors from '../../../utils/colors'

export interface GMTableColumn {
    headerKey: string
    width?: string
    align?: 'left' | 'center' | 'right'
}

export interface GMTableRow {
    cells: (string | number)[]
    highlight?: boolean
}

export interface GMTableDef {
    key: string
    titleKey: string
    descriptionKey?: string
    columns: GMTableColumn[]
    rows: GMTableRow[]
    color: string
}

export interface GMTableCategory {
    key: string
    titleKey: string
    color: string
    tables: GMTableDef[]
}

export const gmTableCategories: GMTableCategory[] = [
    // ─── CATEGORY 1: COMBAT GENERAL (RED) ───
    {
        key: 'combatGeneral',
        titleKey: 'categories.combatGeneral',
        color: colors.neons.red.default,
        tables: [
            {
                key: 'initiativeTurnOrder',
                titleKey: 'tables.initiativeTurnOrder.title',
                descriptionKey: 'tables.initiativeTurnOrder.description',
                color: colors.neons.red.default,
                columns: [
                    { headerKey: 'headers.phase', width: '30%' },
                    { headerKey: 'headers.details' },
                ],
                rows: [
                    { cells: ['t:combat.rollInitiative', 't:combat.rollInitiativeDesc'] },
                    { cells: ['t:combat.highestFirst', 't:combat.highestFirstDesc'] },
                    { cells: ['t:combat.turnActions', 't:combat.turnActionsDesc'] },
                ],
            },
            {
                key: 'combatActions',
                titleKey: 'tables.combatActions.title',
                color: colors.neons.red.default,
                columns: [
                    { headerKey: 'headers.action', width: '30%' },
                    { headerKey: 'headers.description' },
                ],
                rows: [
                    { cells: ['t:combat.attack', 't:combat.attackDesc'] },
                    { cells: ['t:combat.aimedShot', 't:combat.aimedShotDesc'] },
                    { cells: ['t:combat.autofire', 't:combat.autofireDesc'] },
                    { cells: ['t:combat.suppressiveFire', 't:combat.suppressiveFireDesc'] },
                    { cells: ['t:combat.grab', 't:combat.grabDesc'] },
                    { cells: ['t:combat.choke', 't:combat.chokeDesc'] },
                    { cells: ['t:combat.holdAction', 't:combat.holdActionDesc'] },
                    { cells: ['t:combat.run', 't:combat.runDesc'] },
                    { cells: ['t:combat.getUp', 't:combat.getUpDesc'] },
                    { cells: ['t:combat.drawWeapon', 't:combat.drawWeaponDesc'] },
                ],
            },
            {
                key: 'combatModifiers',
                titleKey: 'tables.combatModifiers.title',
                color: colors.neons.red.default,
                columns: [
                    { headerKey: 'headers.situation', width: '50%' },
                    { headerKey: 'headers.modifier', align: 'center' },
                ],
                rows: [
                    { cells: ['t:combat.ambush', '+5'] },
                    { cells: ['t:combat.targetBehindCover', '-4'] },
                    { cells: ['t:combat.aimedShotHead', '-8'] },
                    { cells: ['t:combat.aimedShotHeldItem', '-8'] },
                    { cells: ['t:combat.blindedObscured', '-4'] },
                    { cells: ['t:combat.targetProneRanged', '+2'] },
                    { cells: ['t:combat.targetProneMelee', '-2'] },
                    { cells: ['t:combat.runningTarget', '-2'] },
                    { cells: ['t:combat.shoulderArmBraced', '+1'] },
                    { cells: ['t:combat.firingFromVehicle', '-4'] },
                    { cells: ['t:combat.martialArtsHeadStrike', '-8'] },
                    { cells: ['t:combat.ricochetShot', '-5'] },
                ],
            },
            {
                key: 'coverConcealment',
                titleKey: 'tables.coverConcealment.title',
                color: colors.neons.red.default,
                columns: [
                    { headerKey: 'headers.coverType', width: '50%' },
                    { headerKey: 'headers.sp', align: 'center' },
                ],
                rows: [
                    { cells: ['t:combat.drywall', 5] },
                    { cells: ['t:combat.thinWood', 5] },
                    { cells: ['t:combat.thickWoodThinMetal', 10] },
                    { cells: ['t:combat.stoneBrick', 15] },
                    { cells: ['t:combat.concrete', 20] },
                    { cells: ['t:combat.steel', 25] },
                    { cells: ['t:combat.armored', '30+'] },
                ],
            },
            {
                key: 'woundStateEffects',
                titleKey: 'tables.woundStateEffects.title',
                color: colors.neons.red.default,
                columns: [
                    { headerKey: 'headers.woundState', width: '30%' },
                    { headerKey: 'headers.condition', width: '35%' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: ['t:combat.lightlyWounded', 't:combat.lightlyWoundedCondition', 't:combat.noPenalty'] },
                    { cells: ['t:combat.seriouslyWounded', 't:combat.seriouslyWoundedCondition', 't:combat.minus2AllActions'], highlight: true },
                    { cells: ['t:combat.mortallyWounded', 't:combat.mortallyWoundedCondition', 't:combat.mortallyWoundedEffect'], highlight: true },
                ],
            },
            {
                key: 'deathSaves',
                titleKey: 'tables.deathSaves.title',
                color: colors.neons.red.default,
                columns: [
                    { headerKey: 'headers.mechanic', width: '30%' },
                    { headerKey: 'headers.details' },
                ],
                rows: [
                    { cells: ['t:combat.deathSaveCheck', 't:combat.deathSaveCheckDesc'] },
                    { cells: ['t:combat.deathSaveDV', 't:combat.deathSaveDVDesc'] },
                    { cells: ['t:combat.deathSaveCritBonus', 't:combat.deathSaveCritBonusDesc'] },
                    { cells: ['t:combat.deathSaveFailure', 't:combat.deathSaveFailureDesc'] },
                ],
            },
            {
                key: 'armorAblation',
                titleKey: 'tables.armorAblation.title',
                color: colors.neons.red.default,
                columns: [
                    { headerKey: 'headers.rule', width: '30%' },
                    { headerKey: 'headers.details' },
                ],
                rows: [
                    { cells: ['t:combat.ablation', 't:combat.ablationDesc'] },
                    { cells: ['t:combat.armorDestroyed', 't:combat.armorDestroyedDesc'] },
                    { cells: ['t:combat.armorRepair', 't:combat.armorRepairDesc'] },
                ],
            },
            {
                key: 'hpCalculation',
                titleKey: 'tables.hpCalculation.title',
                descriptionKey: 'tables.hpCalculation.description',
                color: colors.neons.red.default,
                columns: [
                    { headerKey: 'headers.body', align: 'center' },
                    { headerKey: 'headers.will', align: 'center' },
                    { headerKey: 'headers.hp', align: 'center' },
                ],
                rows: [
                    { cells: [2, 2, 20] },
                    { cells: [4, 4, 30] },
                    { cells: [4, 6, 35] },
                    { cells: [6, 4, 35] },
                    { cells: [6, 6, 40] },
                    { cells: [8, 4, 40] },
                    { cells: [6, 8, 45] },
                    { cells: [8, 6, 45] },
                    { cells: [8, 8, 50], highlight: true },
                    { cells: [10, 8, 55] },
                    { cells: [8, 10, 55] },
                    { cells: [10, 10, 60], highlight: true },
                ],
            },
        ],
    },
    // ─── CATEGORY 2: COMBAT RANGED (RED) ───
    {
        key: 'combatRanged',
        titleKey: 'categories.combatRanged',
        color: colors.neons.red.default,
        tables: [
            {
                key: 'singleShotDV',
                titleKey: 'tables.singleShotDV.title',
                color: colors.neons.red.default,
                columns: [
                    { headerKey: 'headers.weaponType', width: '14%' },
                    { headerKey: 'headers.range0_6', align: 'center' },
                    { headerKey: 'headers.range7_12', align: 'center' },
                    { headerKey: 'headers.range13_25', align: 'center' },
                    { headerKey: 'headers.range26_50', align: 'center' },
                    { headerKey: 'headers.range51_100', align: 'center' },
                    { headerKey: 'headers.range101_200', align: 'center' },
                    { headerKey: 'headers.range201_400', align: 'center' },
                    { headerKey: 'headers.range401_800', align: 'center' },
                ],
                rows: [
                    { cells: ['t:weapons.mediumPistol', 13, 15, 20, 25, 30, 30, '-', '-'] },
                    { cells: ['t:weapons.heavyPistol', 13, 15, 20, 25, 30, 30, '-', '-'] },
                    { cells: ['t:weapons.veryHeavyPistol', 13, 15, 20, 25, 30, 30, '-', '-'] },
                    { cells: ['t:weapons.smg', 15, 13, 20, 25, 30, '-', '-', '-'] },
                    { cells: ['t:weapons.heavySmg', 15, 13, 20, 25, 25, 30, '-', '-'] },
                    { cells: ['t:weapons.shotgun', 13, 15, 20, 25, 30, '-', '-', '-'] },
                    { cells: ['t:weapons.assaultRifle', 17, 16, 15, 13, 15, 20, 25, 30] },
                    { cells: ['t:weapons.sniperRifle', 30, 25, 25, 20, 15, 16, 17, 20] },
                    { cells: ['t:weapons.bowCrossbow', 15, 13, 15, 17, 20, 22, '-', '-'] },
                    { cells: ['t:weapons.grenadeLauncher', 16, 15, 15, 17, 20, '-', '-', '-'] },
                    { cells: ['t:weapons.rocketLauncher', 17, 16, 15, 15, 20, 25, '-', '-'] },
                ],
            },
            {
                key: 'autofireDV',
                titleKey: 'tables.autofireDV.title',
                color: colors.neons.red.default,
                columns: [
                    { headerKey: 'headers.weaponType', width: '14%' },
                    { headerKey: 'headers.range0_6', align: 'center' },
                    { headerKey: 'headers.range7_12', align: 'center' },
                    { headerKey: 'headers.range13_25', align: 'center' },
                    { headerKey: 'headers.range26_50', align: 'center' },
                    { headerKey: 'headers.range51_100', align: 'center' },
                    { headerKey: 'headers.range101_200', align: 'center' },
                    { headerKey: 'headers.range201_400', align: 'center' },
                    { headerKey: 'headers.range401_800', align: 'center' },
                ],
                rows: [
                    { cells: ['t:weapons.smg', 17, 15, 22, 27, 32, '-', '-', '-'] },
                    { cells: ['t:weapons.assaultRifle', 19, 18, 17, 15, 17, 22, 27, 32] },
                ],
            },
            {
                key: 'aimedShot',
                titleKey: 'tables.aimedShot.title',
                color: colors.neons.red.default,
                columns: [
                    { headerKey: 'headers.target', width: '25%' },
                    { headerKey: 'headers.modifier', align: 'center', width: '20%' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: ['t:combat.head', '-8', 't:combat.aimedShotHeadEffect'] },
                    { cells: ['t:combat.heldItem', '-8', 't:combat.aimedShotHeldItemEffect'] },
                ],
            },
            {
                key: 'autofireMultiplier',
                titleKey: 'tables.autofireMultiplier.title',
                color: colors.neons.red.default,
                columns: [
                    { headerKey: 'headers.marginOfSuccess', width: '50%' },
                    { headerKey: 'headers.bulletsHit', align: 'center' },
                ],
                rows: [
                    { cells: ['t:combat.beatDVBy0', 1] },
                    { cells: ['t:combat.beatDVBy1_5', 2] },
                    { cells: ['t:combat.beatDVBy6_10', 3] },
                    { cells: ['t:combat.beatDVBy11_15', 4] },
                    { cells: ['t:combat.beatDVBy16plus', 5] },
                ],
            },
            {
                key: 'suppressiveFire',
                titleKey: 'tables.suppressiveFire.title',
                color: colors.neons.red.default,
                columns: [
                    { headerKey: 'headers.rule', width: '30%' },
                    { headerKey: 'headers.details' },
                ],
                rows: [
                    { cells: ['t:combat.suppressiveDV', 't:combat.suppressiveDVDesc'] },
                    { cells: ['t:combat.suppressiveDamage', 't:combat.suppressiveDamageDesc'] },
                    { cells: ['t:combat.suppressiveAmmo', 't:combat.suppressiveAmmoDesc'] },
                    { cells: ['t:combat.suppressiveArea', 't:combat.suppressiveAreaDesc'] },
                ],
            },
            {
                key: 'fumbleRanged',
                titleKey: 'tables.fumbleRanged.title',
                color: colors.neons.red.default,
                columns: [
                    { headerKey: 'headers.d6', align: 'center', width: '15%' },
                    { headerKey: 'headers.result' },
                ],
                rows: [
                    { cells: [1, 't:combat.fumbleRanged1'] },
                    { cells: [2, 't:combat.fumbleRanged2'] },
                    { cells: [3, 't:combat.fumbleRanged3'] },
                    { cells: [4, 't:combat.fumbleRanged4'] },
                    { cells: [5, 't:combat.fumbleRanged5'] },
                    { cells: [6, 't:combat.fumbleRanged6'] },
                ],
            },
        ],
    },
    // ─── CATEGORY 3: COMBAT MELEE (RED) ───
    {
        key: 'combatMelee',
        titleKey: 'categories.combatMelee',
        color: colors.neons.red.default,
        tables: [
            {
                key: 'brawlingDamage',
                titleKey: 'tables.brawlingDamage.title',
                color: colors.neons.red.default,
                columns: [
                    { headerKey: 'headers.bodyStat', width: '50%' },
                    { headerKey: 'headers.damage', align: 'center' },
                ],
                rows: [
                    { cells: ['t:combat.body4OrLess', '1d6'] },
                    { cells: ['t:combat.body5_6', '2d6'] },
                    { cells: ['t:combat.body7_8', '3d6'] },
                    { cells: ['t:combat.body9_10', '4d6'] },
                    { cells: ['t:combat.body11plus', '5d6'] },
                ],
            },
            {
                key: 'martialArts',
                titleKey: 'tables.martialArts.title',
                color: colors.neons.red.default,
                columns: [
                    { headerKey: 'headers.move', width: '25%' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: ['t:combat.strike', 't:combat.strikeEffect'] },
                    { cells: ['t:combat.kick', 't:combat.kickEffect'] },
                    { cells: ['t:combat.block', 't:combat.blockEffect'] },
                    { cells: ['t:combat.disarm', 't:combat.disarmEffect'] },
                    { cells: ['t:combat.throw', 't:combat.throwEffect'] },
                    { cells: ['t:combat.sweep', 't:combat.sweepEffect'] },
                    { cells: ['t:combat.hold', 't:combat.holdEffect'] },
                    { cells: ['t:combat.chokeMA', 't:combat.chokeMAEffect'] },
                ],
            },
            {
                key: 'fumbleMelee',
                titleKey: 'tables.fumbleMelee.title',
                color: colors.neons.red.default,
                columns: [
                    { headerKey: 'headers.d6', align: 'center', width: '15%' },
                    { headerKey: 'headers.result' },
                ],
                rows: [
                    { cells: [1, 't:combat.fumbleMelee1'] },
                    { cells: [2, 't:combat.fumbleMelee2'] },
                    { cells: [3, 't:combat.fumbleMelee3'] },
                    { cells: [4, 't:combat.fumbleMelee4'] },
                    { cells: [5, 't:combat.fumbleMelee5'] },
                    { cells: [6, 't:combat.fumbleMelee6'] },
                ],
            },
            {
                key: 'shotgunRules',
                titleKey: 'tables.shotgunRules.title',
                color: colors.neons.red.default,
                columns: [
                    { headerKey: 'headers.ammoType', width: '25%' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: ['t:combat.shell', 't:combat.shellEffect'] },
                    { cells: ['t:combat.slug', 't:combat.slugEffect'] },
                ],
            },
            {
                key: 'explosionDamage',
                titleKey: 'tables.explosionDamage.title',
                color: colors.neons.red.default,
                columns: [
                    { headerKey: 'headers.distance', width: '30%', align: 'center' },
                    { headerKey: 'headers.damage' },
                ],
                rows: [
                    { cells: ['0m', 't:combat.fullDamage'], highlight: true },
                    { cells: ['1m', 't:combat.fullDamageMinus2'] },
                    { cells: ['2m', 't:combat.fullDamageMinus4'] },
                    { cells: ['3m', 't:combat.fullDamageMinus6'] },
                    { cells: ['4m', 't:combat.fullDamageMinus8'] },
                    { cells: ['5m+', 't:combat.noDamage'] },
                ],
            },
        ],
    },
    // ─── CATEGORY 4: COMBAT INJURIES (ORANGE) ───
    {
        key: 'combatInjuries',
        titleKey: 'categories.combatInjuries',
        color: colors.neons.orange.default,
        tables: [
            {
                key: 'critBody',
                titleKey: 'tables.critBody.title',
                color: colors.neons.orange.default,
                columns: [
                    { headerKey: 'headers.d6', align: 'center', width: '10%' },
                    { headerKey: 'headers.injury', width: '25%' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: [1, 't:injuries.dismemberedArm', 't:injuries.dismemberedArmEffect'] },
                    { cells: [2, 't:injuries.dismemberedHand', 't:injuries.dismemberedHandEffect'] },
                    { cells: [3, 't:injuries.collapsedLung', 't:injuries.collapsedLungEffect'] },
                    { cells: [4, 't:injuries.brokenRibs', 't:injuries.brokenRibsEffect'] },
                    { cells: [5, 't:injuries.brokenArm', 't:injuries.brokenArmEffect'] },
                    { cells: [6, 't:injuries.foreignObjectBody', 't:injuries.foreignObjectBodyEffect'] },
                ],
            },
            {
                key: 'critHead',
                titleKey: 'tables.critHead.title',
                color: colors.neons.orange.default,
                columns: [
                    { headerKey: 'headers.d6', align: 'center', width: '10%' },
                    { headerKey: 'headers.injury', width: '25%' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: [1, 't:injuries.lostEye', 't:injuries.lostEyeEffect'] },
                    { cells: [2, 't:injuries.brainInjury', 't:injuries.brainInjuryEffect'] },
                    { cells: [3, 't:injuries.damagedEye', 't:injuries.damagedEyeEffect'] },
                    { cells: [4, 't:injuries.concussion', 't:injuries.concussionEffect'] },
                    { cells: [5, 't:injuries.brokenJaw', 't:injuries.brokenJawEffect'] },
                    { cells: [6, 't:injuries.foreignObjectHead', 't:injuries.foreignObjectHeadEffect'] },
                ],
            },
        ],
    },
    // ─── CATEGORY 5: SKILLS & CHECKS (BLUE) ───
    {
        key: 'skillsChecks',
        titleKey: 'categories.skillsChecks',
        color: colors.neons.blue.default,
        tables: [
            {
                key: 'difficultyValues',
                titleKey: 'tables.difficultyValues.title',
                color: colors.neons.blue.default,
                columns: [
                    { headerKey: 'headers.difficulty', width: '50%' },
                    { headerKey: 'headers.dv', align: 'center' },
                ],
                rows: [
                    { cells: ['t:skills.everyday', 9] },
                    { cells: ['t:skills.simple', 11] },
                    { cells: ['t:skills.professional', 13] },
                    { cells: ['t:skills.difficult', 15] },
                    { cells: ['t:skills.nearlyImpossible', 17], highlight: true },
                    { cells: ['t:skills.heroic', 21], highlight: true },
                    { cells: ['t:skills.incredible', 24], highlight: true },
                    { cells: ['t:skills.legendary', 29], highlight: true },
                ],
            },
            {
                key: 'complementarySkill',
                titleKey: 'tables.complementarySkill.title',
                descriptionKey: 'tables.complementarySkill.description',
                color: colors.neons.blue.default,
                columns: [
                    { headerKey: 'headers.margin', width: '50%' },
                    { headerKey: 'headers.bonus', align: 'center' },
                ],
                rows: [
                    { cells: ['t:skills.beatDVBy0_4', '+1'] },
                    { cells: ['t:skills.beatDVBy5plus', '+2'] },
                ],
            },
            {
                key: 'skillsByStatTable',
                titleKey: 'tables.skillsByStatTable.title',
                color: colors.neons.blue.default,
                columns: [
                    { headerKey: 'headers.stat', width: '15%' },
                    { headerKey: 'headers.skills' },
                ],
                rows: [
                    { cells: ['INT', 't:skills.intSkills'] },
                    { cells: ['REF', 't:skills.refSkills'] },
                    { cells: ['DEX', 't:skills.dexSkills'] },
                    { cells: ['TECH', 't:skills.techSkills'] },
                    { cells: ['COOL', 't:skills.coolSkills'] },
                    { cells: ['WILL', 't:skills.willSkills'] },
                    { cells: ['EMP', 't:skills.empSkills'] },
                ],
            },
        ],
    },
    // ─── CATEGORY 6: GEAR & ECONOMY (YELLOW) ───
    {
        key: 'gearEconomy',
        titleKey: 'categories.gearEconomy',
        color: colors.neons.yellow.default,
        tables: [
            {
                key: 'priceCategories',
                titleKey: 'tables.priceCategories.title',
                color: colors.neons.yellow.default,
                columns: [
                    { headerKey: 'headers.category', width: '25%' },
                    { headerKey: 'headers.cost', align: 'center', width: '20%' },
                    { headerKey: 'headers.examples' },
                ],
                rows: [
                    { cells: ['t:gear.cheap', '10 eb', 't:gear.cheapExamples'] },
                    { cells: ['t:gear.everyday', '20 eb', 't:gear.everydayExamples'] },
                    { cells: ['t:gear.costly', '50 eb', 't:gear.costlyExamples'] },
                    { cells: ['t:gear.premium', '100 eb', 't:gear.premiumExamples'] },
                    { cells: ['t:gear.expensive', '500 eb', 't:gear.expensiveExamples'] },
                    { cells: ['t:gear.veryExpensive', '1000 eb', 't:gear.veryExpensiveExamples'] },
                    { cells: ['t:gear.luxury', '5000 eb', 't:gear.luxuryExamples'] },
                    { cells: ['t:gear.superLuxury', '10000+ eb', 't:gear.superLuxuryExamples'] },
                ],
            },
            {
                key: 'rangedWeaponStats',
                titleKey: 'tables.rangedWeaponStats.title',
                color: colors.neons.yellow.default,
                columns: [
                    { headerKey: 'headers.weapon' },
                    { headerKey: 'headers.skill', width: '12%' },
                    { headerKey: 'headers.damage', align: 'center' },
                    { headerKey: 'headers.mag', align: 'center' },
                    { headerKey: 'headers.rof', align: 'center' },
                    { headerKey: 'headers.hands', align: 'center' },
                    { headerKey: 'headers.conceal', align: 'center' },
                    { headerKey: 'headers.cost', align: 'center' },
                ],
                rows: [
                    { cells: ['t:weapons.mediumPistol', 't:weapons.handgun', '2d6', 12, 2, '1H', 't:common.yes', '50 eb'] },
                    { cells: ['t:weapons.heavyPistol', 't:weapons.handgun', '3d6', 8, 2, '1H', 't:common.yes', '100 eb'] },
                    { cells: ['t:weapons.veryHeavyPistol', 't:weapons.handgun', '4d6', 8, 1, '1H', 't:common.no', '100 eb'] },
                    { cells: ['t:weapons.smg', 't:weapons.handgun', '2d6', 30, 1, '1H', 't:common.yes', '100 eb'] },
                    { cells: ['t:weapons.heavySmg', 't:weapons.handgun', '3d6', 40, 1, '1H', 't:common.no', '100 eb'] },
                    { cells: ['t:weapons.shotgun', 't:weapons.shoulderArms', '5d6', 4, 1, '2H', 't:common.no', '500 eb'] },
                    { cells: ['t:weapons.assaultRifle', 't:weapons.shoulderArms', '5d6', 25, 1, '2H', 't:common.no', '500 eb'] },
                    { cells: ['t:weapons.sniperRifle', 't:weapons.shoulderArms', '5d6', 4, 1, '2H', 't:common.no', '500 eb'] },
                    { cells: ['t:weapons.bowCrossbow', 't:weapons.archery', '4d6', '-', 1, '2H', 't:common.no', '100 eb'] },
                    { cells: ['t:weapons.grenadeLauncher', 't:weapons.heavyWeapons', '6d6', 2, 1, '2H', 't:common.no', '500 eb'] },
                    { cells: ['t:weapons.rocketLauncher', 't:weapons.heavyWeapons', '8d6', 1, 1, '2H', 't:common.no', '500 eb'] },
                ],
            },
            {
                key: 'meleeWeaponStats',
                titleKey: 'tables.meleeWeaponStats.title',
                color: colors.neons.yellow.default,
                columns: [
                    { headerKey: 'headers.weapon' },
                    { headerKey: 'headers.damage', align: 'center' },
                    { headerKey: 'headers.rof', align: 'center' },
                    { headerKey: 'headers.hands', align: 'center' },
                    { headerKey: 'headers.conceal', align: 'center' },
                    { headerKey: 'headers.cost', align: 'center' },
                ],
                rows: [
                    { cells: ['t:weapons.lightMelee', '1d6', 2, '1H', 't:common.yes', '50 eb'] },
                    { cells: ['t:weapons.mediumMelee', '2d6', 2, '1-2H', 't:common.no', '50 eb'] },
                    { cells: ['t:weapons.heavyMelee', '3d6', 2, '2H', 't:common.no', '100 eb'] },
                    { cells: ['t:weapons.veryHeavyMelee', '4d6', 1, '2H', 't:common.no', '500 eb'] },
                ],
            },
            {
                key: 'exoticWeapons',
                titleKey: 'tables.exoticWeapons.title',
                color: colors.neons.yellow.default,
                columns: [
                    { headerKey: 'headers.weapon' },
                    { headerKey: 'headers.cost', align: 'center', width: '15%' },
                    { headerKey: 'headers.notes' },
                ],
                rows: [
                    { cells: ['t:weapons.airPistol', '100 eb', 't:weapons.airPistolNotes'] },
                    { cells: ['t:weapons.battleglove', '1000 eb', 't:weapons.battlegloveNotes'] },
                    { cells: ['t:weapons.hurricaneAssault', '5000 eb', 't:weapons.hurricaneAssaultNotes'] },
                    { cells: ['t:weapons.dartgun', '100 eb', 't:weapons.dartgunNotes'] },
                    { cells: ['t:weapons.flamethrower', '500 eb', 't:weapons.flamethrowerNotes'] },
                    { cells: ['t:weapons.kendachiMonoThree', '5000 eb', 't:weapons.kendachiMonoThreeNotes'] },
                    { cells: ['t:weapons.malorian3516', '10000 eb', 't:weapons.malorian3516Notes'] },
                    { cells: ['t:weapons.microwaver', '500 eb', 't:weapons.microwaverNotes'] },
                    { cells: ['t:weapons.militechCowboy', '5000 eb', 't:weapons.militechCowboyNotes'] },
                    { cells: ['t:weapons.rhinemetallRailgun', '5000 eb', 't:weapons.rhinemetallRailgunNotes'] },
                    { cells: ['t:weapons.shrieker', '500 eb', 't:weapons.shriekerNotes'] },
                    { cells: ['t:weapons.stunBaton', '100 eb', 't:weapons.stunBatonNotes'] },
                    { cells: ['t:weapons.stunGun', '100 eb', 't:weapons.stunGunNotes'] },
                    { cells: ['t:weapons.tsunamiHelix', '5000 eb', 't:weapons.tsunamiHelixNotes'] },
                ],
            },
            {
                key: 'armorTypes',
                titleKey: 'tables.armorTypes.title',
                color: colors.neons.yellow.default,
                columns: [
                    { headerKey: 'headers.armor' },
                    { headerKey: 'headers.sp', align: 'center' },
                    { headerKey: 'headers.penalty', align: 'center' },
                    { headerKey: 'headers.cost', align: 'center' },
                ],
                rows: [
                    { cells: ['t:gear.leathers', 4, 't:common.none', '20 eb'] },
                    { cells: ['t:gear.kevlar', 7, 't:common.none', '50 eb'] },
                    { cells: ['t:gear.lightArmorjack', 11, 't:common.none', '100 eb'] },
                    { cells: ['t:gear.bodyweightSuit', 11, 't:common.none', '1000 eb'] },
                    { cells: ['t:gear.mediumArmorjack', 12, '-2', '100 eb'] },
                    { cells: ['t:gear.heavyArmorjack', 13, '-2', '500 eb'] },
                    { cells: ['t:gear.flak', 15, '-4', '500 eb'] },
                    { cells: ['t:gear.metalgear', 18, '-4', '5000 eb'], highlight: true },
                    { cells: ['t:gear.bulletproofShield', '10 HP', 't:common.none', '100 eb'] },
                ],
            },
            {
                key: 'ammoTypes',
                titleKey: 'tables.ammoTypes.title',
                color: colors.neons.yellow.default,
                columns: [
                    { headerKey: 'headers.ammoType' },
                    { headerKey: 'headers.cost', align: 'center', width: '15%' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: ['t:gear.ammoBasic', '10 eb', 't:gear.ammoBasicEffect'] },
                    { cells: ['t:gear.ammoAP', '100 eb', 't:gear.ammoAPEffect'] },
                    { cells: ['t:gear.ammoBiotoxin', '500 eb', 't:gear.ammoBiotoxinEffect'] },
                    { cells: ['t:gear.ammoEMP', '100 eb', 't:gear.ammoEMPEffect'] },
                    { cells: ['t:gear.ammoExpansive', '100 eb', 't:gear.ammoExpansiveEffect'] },
                    { cells: ['t:gear.ammoFlashbang', '100 eb', 't:gear.ammoFlashbangEffect'] },
                    { cells: ['t:gear.ammoIncendiary', '100 eb', 't:gear.ammoIncendiaryEffect'] },
                    { cells: ['t:gear.ammoPoison', '500 eb', 't:gear.ammoPoisonEffect'] },
                    { cells: ['t:gear.ammoRubber', '10 eb', 't:gear.ammoRubberEffect'] },
                    { cells: ['t:gear.ammoSleep', '500 eb', 't:gear.ammoSleepEffect'] },
                    { cells: ['t:gear.ammoSmoke', '50 eb', 't:gear.ammoSmokeEffect'] },
                    { cells: ['t:gear.ammoTeargas', '50 eb', 't:gear.ammoTeargasEffect'] },
                ],
            },
            {
                key: 'weaponAttachments',
                titleKey: 'tables.weaponAttachments.title',
                color: colors.neons.yellow.default,
                columns: [
                    { headerKey: 'headers.attachment' },
                    { headerKey: 'headers.cost', align: 'center', width: '15%' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: ['t:gear.drumMagazine', '500 eb', 't:gear.drumMagazineEffect'] },
                    { cells: ['t:gear.extendedMagazine', '100 eb', 't:gear.extendedMagazineEffect'] },
                    { cells: ['t:gear.bayonet', '50 eb', 't:gear.bayonetEffect'] },
                    { cells: ['t:gear.underbarrelGL', '500 eb', 't:gear.underbarrelGLEffect'] },
                    { cells: ['t:gear.infraredScope', '500 eb', 't:gear.infraredScopeEffect'] },
                    { cells: ['t:gear.snipingScope', '500 eb', 't:gear.snipingScopeEffect'] },
                    { cells: ['t:gear.suppressor', '100 eb', 't:gear.suppressorEffect'] },
                ],
            },
            {
                key: 'weaponQuality',
                titleKey: 'tables.weaponQuality.title',
                color: colors.neons.yellow.default,
                columns: [
                    { headerKey: 'headers.quality' },
                    { headerKey: 'headers.costModifier', align: 'center' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: ['t:gear.poor', 't:gear.halfCost', 't:gear.poorEffect'] },
                    { cells: ['t:gear.standard', 't:gear.normalCost', 't:gear.standardEffect'] },
                    { cells: ['t:gear.excellent', 't:gear.tripleCost', 't:gear.excellentEffect'] },
                ],
            },
            {
                key: 'equipmentList',
                titleKey: 'tables.equipmentList.title',
                color: colors.neons.yellow.default,
                columns: [
                    { headerKey: 'headers.item' },
                    { headerKey: 'headers.cost', align: 'center' },
                ],
                rows: [
                    { cells: ['t:gear.agent', '100 eb'] },
                    { cells: ['t:gear.airhypo', '50 eb'] },
                    { cells: ['t:gear.antiSmogMask', '20 eb'] },
                    { cells: ['t:gear.audioRecorder', '100 eb'] },
                    { cells: ['t:gear.binoculars', '50 eb'] },
                    { cells: ['t:gear.bugDetector', '500 eb'] },
                    { cells: ['t:gear.carryall', '20 eb'] },
                    { cells: ['t:gear.computer', '50 eb'] },
                    { cells: ['t:gear.disposableCellPhone', '10 eb'] },
                    { cells: ['t:gear.ductTape', '20 eb'] },
                    { cells: ['t:gear.flashlight', '20 eb'] },
                    { cells: ['t:gear.foodStick', '10 eb'] },
                    { cells: ['t:gear.glowPaint', '20 eb'] },
                    { cells: ['t:gear.glowStick', '10 eb'] },
                    { cells: ['t:gear.grappleGun', '100 eb'] },
                    { cells: ['t:gear.handcuffs', '50 eb'] },
                    { cells: ['t:gear.homingTracer', '500 eb'] },
                    { cells: ['t:gear.inflatableBed', '20 eb'] },
                    { cells: ['t:gear.lockPickingSet', '20 eb'] },
                    { cells: ['t:gear.medscanner', '1000 eb'] },
                    { cells: ['t:gear.medtechBag', '100 eb'] },
                    { cells: ['t:gear.memoryChip', '10 eb'] },
                    { cells: ['t:gear.mre', '10 eb'] },
                    { cells: ['t:gear.personalCarePak', '20 eb'] },
                    { cells: ['t:gear.pocketAmplifier', '50 eb'] },
                    { cells: ['t:gear.radarDetector', '500 eb'] },
                    { cells: ['t:gear.radioCommunicator', '100 eb'] },
                    { cells: ['t:gear.radioScanner', '50 eb'] },
                    { cells: ['t:gear.roadFlare', '10 eb'] },
                    { cells: ['t:gear.rope', '20 eb'] },
                    { cells: ['t:gear.scrambler', '500 eb'] },
                    { cells: ['t:gear.smartGlasses', '500 eb'] },
                    { cells: ['t:gear.techBag', '100 eb'] },
                    { cells: ['t:gear.techtool', '100 eb'] },
                    { cells: ['t:gear.tent', '50 eb'] },
                    { cells: ['t:gear.vialBiotoxin', '500 eb'] },
                    { cells: ['t:gear.vialPoison', '500 eb'] },
                    { cells: ['t:gear.videoCamera', '100 eb'] },
                    { cells: ['t:gear.virtualityGoggles', '100 eb'] },
                ],
            },
            {
                key: 'fashionCategories',
                titleKey: 'tables.fashionCategories.title',
                color: colors.neons.yellow.default,
                columns: [
                    { headerKey: 'headers.style' },
                    { headerKey: 'headers.cost', align: 'center', width: '15%' },
                    { headerKey: 'headers.description' },
                ],
                rows: [
                    { cells: ['t:gear.bagLadyChic', '10 eb', 't:gear.bagLadyChicDesc'] },
                    { cells: ['t:gear.genericChic', '20 eb', 't:gear.genericChicDesc'] },
                    { cells: ['t:gear.leisurewear', '20 eb', 't:gear.leisurewearDesc'] },
                    { cells: ['t:gear.businesswear', '50 eb', 't:gear.businesswearDesc'] },
                    { cells: ['t:gear.highFashion', '100 eb', 't:gear.highFashionDesc'] },
                    { cells: ['t:gear.urbanFlash', '100 eb', 't:gear.urbanFlashDesc'] },
                    { cells: ['t:gear.bohemian', '100 eb', 't:gear.bohemianDesc'] },
                    { cells: ['t:gear.asiaPop', '100 eb', 't:gear.asiaPopDesc'] },
                    { cells: ['t:gear.nomadLeathers', '100 eb', 't:gear.nomadLeathersDesc'] },
                    { cells: ['t:gear.gangColors', '20 eb', 't:gear.gangColorsDesc'] },
                ],
            },
            {
                key: 'nightMarketAvailability',
                titleKey: 'tables.nightMarketAvailability.title',
                color: colors.neons.yellow.default,
                columns: [
                    { headerKey: 'headers.rule', width: '30%' },
                    { headerKey: 'headers.details' },
                ],
                rows: [
                    { cells: ['t:gear.nightMarketAccess', 't:gear.nightMarketAccessDesc'] },
                    { cells: ['t:gear.nightMarketRare', 't:gear.nightMarketRareDesc'] },
                ],
            },
            {
                key: 'nightMarketHaggling',
                titleKey: 'tables.nightMarketHaggling.title',
                color: colors.neons.yellow.default,
                columns: [
                    { headerKey: 'headers.rule', width: '30%' },
                    { headerKey: 'headers.details' },
                ],
                rows: [
                    { cells: ['t:gear.hagglingCheck', 't:gear.hagglingCheckDesc'] },
                    { cells: ['t:gear.hagglingDiscount', 't:gear.hagglingDiscountDesc'] },
                ],
            },
            {
                key: 'lifestyleHousing',
                titleKey: 'tables.lifestyleHousing.title',
                color: colors.neons.yellow.default,
                columns: [
                    { headerKey: 'headers.type', width: '30%' },
                    { headerKey: 'headers.cost', align: 'center', width: '20%' },
                ],
                rows: [
                    { cells: ['t:gear.kibble', 't:common.free'], highlight: true },
                    { cells: ['t:gear.prepak', '20 eb/mo'] },
                    { cells: ['t:gear.goodMeal', '100 eb/mo'] },
                    { cells: ['t:gear.containerSquat', '0 eb'], highlight: true },
                    { cells: ['t:gear.cubeHotel', '500 eb/mo'] },
                    { cells: ['t:gear.cargoContainer', '1000 eb/mo'] },
                    { cells: ['t:gear.conapt', '2000 eb/mo'] },
                    { cells: ['t:gear.apartment', '5000 eb/mo'] },
                ],
            },
        ],
    },
    // ─── CATEGORY 7: CYBERWARE (PINK) ───
    {
        key: 'cyberware',
        titleKey: 'categories.cyberware',
        color: colors.neons.pink.default,
        tables: [
            {
                key: 'fashionware',
                titleKey: 'tables.fashionware.title',
                descriptionKey: 'tables.fashionware.description',
                color: colors.neons.pink.default,
                columns: [
                    { headerKey: 'headers.cyberware' },
                    { headerKey: 'headers.cost', align: 'center', width: '15%' },
                    { headerKey: 'headers.hl', align: 'center', width: '10%' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: ['t:cyber.biomonitorFashion', '100 eb', 0, 't:cyber.biomonitorFashionEffect'] },
                    { cells: ['t:cyber.chemskin', '100 eb', 0, 't:cyber.chemskinEffect'] },
                    { cells: ['t:cyber.empThreading', '10 eb', 0, 't:cyber.empThreadingEffect'] },
                    { cells: ['t:cyber.lightTattoo', '100 eb', 0, 't:cyber.lightTattooEffect'] },
                    { cells: ['t:cyber.shiftTacts', '100 eb', 0, 't:cyber.shiftTactsEffect'] },
                    { cells: ['t:cyber.techhair', '100 eb', 0, 't:cyber.techhairEffect'] },
                ],
            },
            {
                key: 'neuralware',
                titleKey: 'tables.neuralware.title',
                color: colors.neons.pink.default,
                columns: [
                    { headerKey: 'headers.cyberware' },
                    { headerKey: 'headers.cost', align: 'center', width: '12%' },
                    { headerKey: 'headers.hl', align: 'center', width: '8%' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: ['t:cyber.neuralLink', '500 eb', 7, 't:cyber.neuralLinkEffect'], highlight: true },
                    { cells: ['t:cyber.braindanceRecorder', '500 eb', 7, 't:cyber.braindanceRecorderEffect'] },
                    { cells: ['t:cyber.interfacePlugs', '500 eb', 7, 't:cyber.interfacePlugsEffect'] },
                    { cells: ['t:cyber.kerenzikov', '500 eb', 14, 't:cyber.kerenzikovEffect'] },
                    { cells: ['t:cyber.sandevistan', '1000 eb', 14, 't:cyber.sandevistanEffect'] },
                    { cells: ['t:cyber.speedware', '1000 eb', 14, 't:cyber.speedwareEffect'], highlight: true },
                ],
            },
            {
                key: 'cyberoptics',
                titleKey: 'tables.cyberoptics.title',
                color: colors.neons.pink.default,
                columns: [
                    { headerKey: 'headers.cyberware' },
                    { headerKey: 'headers.cost', align: 'center', width: '12%' },
                    { headerKey: 'headers.hl', align: 'center', width: '8%' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: ['t:cyber.cybereye', '100 eb', 7, 't:cyber.cybereyeEffect'], highlight: true },
                    { cells: ['t:cyber.antiDazzle', '100 eb', 2, 't:cyber.antiDazzleEffect'] },
                    { cells: ['t:cyber.chyronDisplay', '100 eb', 2, 't:cyber.chyronDisplayEffect'] },
                    { cells: ['t:cyber.imageEnhance', '500 eb', 2, 't:cyber.imageEnhanceEffect'] },
                    { cells: ['t:cyber.lowLightIRUV', '500 eb', 2, 't:cyber.lowLightIRUVEffect'] },
                    { cells: ['t:cyber.microOptics', '500 eb', 2, 't:cyber.microOpticsEffect'] },
                    { cells: ['t:cyber.targetingScope', '500 eb', 2, 't:cyber.targetingScopeEffect'] },
                    { cells: ['t:cyber.teleOptics', '500 eb', 2, 't:cyber.teleOpticsEffect'] },
                    { cells: ['t:cyber.virtuality', '100 eb', 2, 't:cyber.virtualityEffect'] },
                ],
            },
            {
                key: 'cyberaudio',
                titleKey: 'tables.cyberaudio.title',
                color: colors.neons.pink.default,
                columns: [
                    { headerKey: 'headers.cyberware' },
                    { headerKey: 'headers.cost', align: 'center', width: '12%' },
                    { headerKey: 'headers.hl', align: 'center', width: '8%' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: ['t:cyber.cyberaudioSuite', '500 eb', 7, 't:cyber.cyberaudioSuiteEffect'], highlight: true },
                    { cells: ['t:cyber.amplifiedHearing', '100 eb', 3, 't:cyber.amplifiedHearingEffect'] },
                    { cells: ['t:cyber.audioRecorderCyber', '100 eb', 3, 't:cyber.audioRecorderCyberEffect'] },
                    { cells: ['t:cyber.bugDetectorCyber', '500 eb', 3, 't:cyber.bugDetectorCyberEffect'] },
                    { cells: ['t:cyber.homingTracerCyber', '500 eb', 3, 't:cyber.homingTracerCyberEffect'] },
                    { cells: ['t:cyber.internalAgent', '100 eb', 3, 't:cyber.internalAgentEffect'] },
                    { cells: ['t:cyber.levelDamper', '100 eb', 3, 't:cyber.levelDamperEffect'] },
                    { cells: ['t:cyber.radioCommunicatorCyber', '100 eb', 3, 't:cyber.radioCommunicatorCyberEffect'] },
                    { cells: ['t:cyber.radioScannerCyber', '100 eb', 3, 't:cyber.radioScannerCyberEffect'] },
                    { cells: ['t:cyber.scramblerCyber', '500 eb', 3, 't:cyber.scramblerCyberEffect'] },
                ],
            },
            {
                key: 'internalCyberware',
                titleKey: 'tables.internalCyberware.title',
                color: colors.neons.pink.default,
                columns: [
                    { headerKey: 'headers.cyberware' },
                    { headerKey: 'headers.cost', align: 'center', width: '12%' },
                    { headerKey: 'headers.hl', align: 'center', width: '8%' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: ['t:cyber.biomonitorInternal', '100 eb', 2, 't:cyber.biomonitorInternalEffect'] },
                    { cells: ['t:cyber.toxinBinders', '100 eb', 2, 't:cyber.toxinBindersEffect'] },
                    { cells: ['t:cyber.nasalFilters', '100 eb', 2, 't:cyber.nasalFiltersEffect'] },
                    { cells: ['t:cyber.independentAirSupply', '1000 eb', 2, 't:cyber.independentAirSupplyEffect'] },
                    { cells: ['t:cyber.cybersnake', '1000 eb', 14, 't:cyber.cybersnakeEffect'] },
                ],
            },
            {
                key: 'externalCyberware',
                titleKey: 'tables.externalCyberware.title',
                color: colors.neons.pink.default,
                columns: [
                    { headerKey: 'headers.cyberware' },
                    { headerKey: 'headers.cost', align: 'center', width: '12%' },
                    { headerKey: 'headers.hl', align: 'center', width: '8%' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: ['t:cyber.hiddenHolster', '500 eb', 7, 't:cyber.hiddenHolsterEffect'] },
                    { cells: ['t:cyber.skinWeave', '500 eb', 7, 't:cyber.skinWeaveEffect'] },
                    { cells: ['t:cyber.subdermalArmor', '1000 eb', 14, 't:cyber.subdermalArmorEffect'] },
                    { cells: ['t:cyber.subdermalGrip', '100 eb', 3, 't:cyber.subdermalGripEffect'] },
                ],
            },
            {
                key: 'cyberlimbs',
                titleKey: 'tables.cyberlimbs.title',
                color: colors.neons.pink.default,
                columns: [
                    { headerKey: 'headers.cyberware' },
                    { headerKey: 'headers.cost', align: 'center', width: '12%' },
                    { headerKey: 'headers.hl', align: 'center', width: '8%' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: ['t:cyber.cyberarm', '500 eb', 7, 't:cyber.cyberarmEffect'] },
                    { cells: ['t:cyber.cyberleg', '500 eb', 7, 't:cyber.cyberlegEffect'] },
                    { cells: ['t:cyber.bigKnucks', '100 eb', 3, 't:cyber.bigKnucksEffect'] },
                    { cells: ['t:cyber.rippers', '500 eb', 3, 't:cyber.rippersEffect'] },
                    { cells: ['t:cyber.scratchers', '100 eb', 2, 't:cyber.scratchersEffect'] },
                    { cells: ['t:cyber.wolvers', '500 eb', 7, 't:cyber.wolversEffect'] },
                    { cells: ['t:cyber.grappleHand', '100 eb', 3, 't:cyber.grappleHandEffect'] },
                    { cells: ['t:cyber.jumpBoosters', '500 eb', 3, 't:cyber.jumpBoostersEffect'] },
                    { cells: ['t:cyber.skateFoot', '100 eb', 2, 't:cyber.skateFootEffect'] },
                    { cells: ['t:cyber.talonFoot', '100 eb', 2, 't:cyber.talonFootEffect'] },
                    { cells: ['t:cyber.toolHand', '100 eb', 2, 't:cyber.toolHandEffect'] },
                    { cells: ['t:cyber.popUpMelee', '500 eb', 7, 't:cyber.popUpMeleeEffect'] },
                    { cells: ['t:cyber.popUpRanged', '500 eb', 7, 't:cyber.popUpRangedEffect'] },
                ],
            },
            {
                key: 'borgware',
                titleKey: 'tables.borgware.title',
                color: colors.neons.pink.default,
                columns: [
                    { headerKey: 'headers.cyberware' },
                    { headerKey: 'headers.cost', align: 'center', width: '12%' },
                    { headerKey: 'headers.hl', align: 'center', width: '8%' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: ['t:cyber.artificialShoulderMount', '1000 eb', 14, 't:cyber.artificialShoulderMountEffect'] },
                    { cells: ['t:cyber.linearFrameSigma', '5000 eb', 14, 't:cyber.linearFrameSigmaEffect'] },
                    { cells: ['t:cyber.linearFrameBeta', '10000 eb', 14, 't:cyber.linearFrameBetaEffect'] },
                    { cells: ['t:cyber.multiOpticMount', '1000 eb', 14, 't:cyber.multiOpticMountEffect'] },
                    { cells: ['t:cyber.sensorArray', '1000 eb', 14, 't:cyber.sensorArrayEffect'] },
                ],
            },
            {
                key: 'humanityEmpathy',
                titleKey: 'tables.humanityEmpathy.title',
                color: colors.neons.pink.default,
                columns: [
                    { headerKey: 'headers.rule', width: '30%' },
                    { headerKey: 'headers.details' },
                ],
                rows: [
                    { cells: ['t:cyber.startingHumanity', 't:cyber.startingHumanityDesc'] },
                    { cells: ['t:cyber.loseHumanity', 't:cyber.loseHumanityDesc'] },
                    { cells: ['t:cyber.empCalc', 't:cyber.empCalcDesc'] },
                    { cells: ['t:cyber.cyberpsychosis', 't:cyber.cyberpsychosisDesc'], highlight: true },
                    { cells: ['t:cyber.therapy', 't:cyber.therapyDesc'] },
                ],
            },
        ],
    },
    // ─── CATEGORY 8: NETRUNNING (CYAN) ───
    {
        key: 'netrunning',
        titleKey: 'categories.netrunning',
        color: colors.neons.cyan.default,
        tables: [
            {
                key: 'netFloorDV',
                titleKey: 'tables.netFloorDV.title',
                color: colors.neons.cyan.default,
                columns: [
                    { headerKey: 'headers.floor', align: 'center', width: '40%' },
                    { headerKey: 'headers.dv', align: 'center' },
                ],
                rows: [
                    { cells: ['t:net.floor1', 6] },
                    { cells: ['t:net.floor2', 8] },
                    { cells: ['t:net.floor3', 10] },
                    { cells: ['t:net.floor4', 12] },
                    { cells: ['t:net.floor5', 14] },
                    { cells: ['t:net.floor6', 16] },
                    { cells: ['t:net.floor7', 18] },
                    { cells: ['t:net.floor8', 20], highlight: true },
                ],
            },
            {
                key: 'programsList',
                titleKey: 'tables.programsList.title',
                color: colors.neons.cyan.default,
                columns: [
                    { headerKey: 'headers.program' },
                    { headerKey: 'headers.type', width: '15%' },
                    { headerKey: 'headers.cost', align: 'center', width: '12%' },
                    { headerKey: 'headers.atkDef', align: 'center', width: '10%' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: ['t:net.banhammer', 't:net.antiPersonnel', '1000 eb', 'ATK 2', 't:net.banhammerEffect'] },
                    { cells: ['t:net.hellbolt', 't:net.antiPersonnel', '5000 eb', 'ATK 6', 't:net.hellboltEffect'] },
                    { cells: ['t:net.nerveBurner', 't:net.antiPersonnel', '500 eb', 'ATK 0', 't:net.nerveBurnerEffect'] },
                    { cells: ['t:net.poisonFlatline', 't:net.antiPersonnel', '5000 eb', 'ATK 2', 't:net.poisonFlatlineEffect'] },
                    { cells: ['t:net.superglue', 't:net.antiPersonnel', '500 eb', 'ATK 0', 't:net.superglueEffect'] },
                    { cells: ['t:net.sword', 't:net.antiPersonnel', '100 eb', 'ATK 0', 't:net.swordEffect'] },
                    { cells: ['t:net.vrizzbolt', 't:net.antiPersonnel', '1000 eb', 'ATK 2', 't:net.vrizzboltEffect'] },
                    { cells: ['t:net.eraser', 't:net.antiProgram', '100 eb', 'ATK 0', 't:net.eraserEffect'] },
                    { cells: ['t:net.swordfish', 't:net.antiProgram', '500 eb', 'ATK 0', 't:net.swordfishEffect'] },
                    { cells: ['t:net.worm', 't:net.antiProgram', '1000 eb', 'ATK 4', 't:net.wormEffect'] },
                    { cells: ['t:net.armor', 't:net.booster', '500 eb', '+4 DEF', 't:net.armorEffect'] },
                    { cells: ['t:net.flak', 't:net.booster', '1000 eb', '+2 DEF', 't:net.flakEffect'] },
                    { cells: ['t:net.shield', 't:net.booster', '100 eb', '+2 DEF', 't:net.shieldEffect'] },
                    { cells: ['t:net.speedyGonzalvez', 't:net.booster', '1000 eb', '+4 SPD', 't:net.speedyGonzalvezEffect'] },
                    { cells: ['t:net.seeYa', 't:net.defender', '100 eb', 'DEF 2', 't:net.seeYaEffect'] },
                    { cells: ['t:net.smoke', 't:net.defender', '500 eb', 'DEF 4', 't:net.smokeEffect'] },
                    { cells: ['t:net.stun', 't:net.defender', '500 eb', 'DEF 0', 't:net.stunEffect'] },
                ],
            },
            {
                key: 'blackIce',
                titleKey: 'tables.blackIce.title',
                color: colors.neons.cyan.default,
                columns: [
                    { headerKey: 'headers.ice' },
                    { headerKey: 'headers.per', align: 'center' },
                    { headerKey: 'headers.spd', align: 'center' },
                    { headerKey: 'headers.atk', align: 'center' },
                    { headerKey: 'headers.def', align: 'center' },
                    { headerKey: 'headers.rez', align: 'center' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: ['t:net.asp', 4, 6, 2, 2, 15, 't:net.aspEffect'] },
                    { cells: ['t:net.giant', 2, 4, 4, 2, 25, 't:net.giantEffect'] },
                    { cells: ['t:net.hellhound', 6, 6, 6, 2, 20, 't:net.hellhoundEffect'] },
                    { cells: ['t:net.kraken', 6, 8, 8, 4, 30, 't:net.krakenEffect'], highlight: true },
                    { cells: ['t:net.liche', 4, 4, 4, 2, 15, 't:net.licheEffect'] },
                    { cells: ['t:net.raven', 8, 4, 0, 6, 15, 't:net.ravenEffect'] },
                    { cells: ['t:net.scorpion', 4, 4, 2, 2, 15, 't:net.scorpionEffect'] },
                    { cells: ['t:net.skunk', 2, 2, 0, 4, 10, 't:net.skunkEffect'] },
                    { cells: ['t:net.wisp', 6, 2, 0, 2, 10, 't:net.wispEffect'] },
                    { cells: ['t:net.dragon', 8, 8, 8, 6, 40, 't:net.dragonEffect'], highlight: true },
                ],
            },
            {
                key: 'demonReference',
                titleKey: 'tables.demonReference.title',
                color: colors.neons.cyan.default,
                columns: [
                    { headerKey: 'headers.demon' },
                    { headerKey: 'headers.per', align: 'center' },
                    { headerKey: 'headers.spd', align: 'center' },
                    { headerKey: 'headers.atk', align: 'center' },
                    { headerKey: 'headers.def', align: 'center' },
                    { headerKey: 'headers.rez', align: 'center' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: ['t:net.demonBasic', 2, 2, 0, 4, 20, 't:net.demonBasicEffect'] },
                    { cells: ['t:net.demonAdvanced', 4, 4, 0, 6, 30, 't:net.demonAdvancedEffect'] },
                ],
            },
            {
                key: 'netrunnerActions',
                titleKey: 'tables.netrunnerActions.title',
                color: colors.neons.cyan.default,
                columns: [
                    { headerKey: 'headers.action', width: '20%' },
                    { headerKey: 'headers.description' },
                ],
                rows: [
                    { cells: ['t:net.interface', 't:net.interfaceDesc'] },
                    { cells: ['t:net.jackInOut', 't:net.jackInOutDesc'] },
                    { cells: ['t:net.activateProgram', 't:net.activateProgramDesc'] },
                    { cells: ['t:net.backdoor', 't:net.backdoorDesc'] },
                    { cells: ['t:net.cloak', 't:net.cloakDesc'] },
                    { cells: ['t:net.control', 't:net.controlDesc'] },
                    { cells: ['t:net.eyeDee', 't:net.eyeDeeDesc'] },
                    { cells: ['t:net.pathfinder', 't:net.pathfinderDesc'] },
                    { cells: ['t:net.scanner', 't:net.scannerDesc'] },
                    { cells: ['t:net.slide', 't:net.slideDesc'] },
                    { cells: ['t:net.virus', 't:net.virusDesc'] },
                    { cells: ['t:net.zap', 't:net.zapDesc'] },
                ],
            },
            {
                key: 'interfaceCheckDVs',
                titleKey: 'tables.interfaceCheckDVs.title',
                color: colors.neons.cyan.default,
                columns: [
                    { headerKey: 'headers.action', width: '40%' },
                    { headerKey: 'headers.dv' },
                ],
                rows: [
                    { cells: ['t:net.controlDevice', 't:net.controlDeviceDV'] },
                    { cells: ['t:net.crackPassword', 't:net.crackPasswordDV'] },
                    { cells: ['t:net.activateDeactivateIce', 't:net.activateDeactivateIceDV'] },
                    { cells: ['t:net.backdoorAction', 't:net.backdoorActionDV'] },
                    { cells: ['t:net.cloakAction', 't:net.cloakActionDV'] },
                ],
            },
        ],
    },
    // ─── CATEGORY 9: VEHICLE COMBAT (ORANGE) ───
    {
        key: 'vehicleCombat',
        titleKey: 'categories.vehicleCombat',
        color: colors.neons.orange.default,
        tables: [
            {
                key: 'vehicleStats',
                titleKey: 'tables.vehicleStats.title',
                color: colors.neons.orange.default,
                columns: [
                    { headerKey: 'headers.vehicle' },
                    { headerKey: 'headers.sp', align: 'center' },
                    { headerKey: 'headers.sdp', align: 'center' },
                    { headerKey: 'headers.move', align: 'center' },
                    { headerKey: 'headers.seats', align: 'center' },
                    { headerKey: 'headers.cost', align: 'center' },
                ],
                rows: [
                    { cells: ['t:vehicles.compactGroundcar', 10, 30, 20, 4, '20000 eb'] },
                    { cells: ['t:vehicles.sedanGroundcar', 10, 30, 25, 4, '30000 eb'] },
                    { cells: ['t:vehicles.sportGroundcar', 10, 30, 35, 2, '50000 eb'] },
                    { cells: ['t:vehicles.luxuryGroundcar', 15, 40, 30, 4, '100000 eb'] },
                    { cells: ['t:vehicles.superGroundcar', 15, 40, 45, 2, '200000 eb'] },
                    { cells: ['t:vehicles.motorcycle', 5, 15, 35, 2, '10000 eb'] },
                    { cells: ['t:vehicles.jetSki', 5, 15, 25, 2, '10000 eb'] },
                    { cells: ['t:vehicles.roadbike', 5, 15, 40, 1, '15000 eb'] },
                    { cells: ['t:vehicles.av4', 15, 40, 40, 6, '500000 eb'] },
                    { cells: ['t:vehicles.helicopter', 10, 30, 30, 6, '200000 eb'] },
                    { cells: ['t:vehicles.speedboat', 10, 30, 30, 6, '50000 eb'] },
                    { cells: ['t:vehicles.cabinCruiser', 15, 40, 20, 10, '100000 eb'] },
                ],
            },
            {
                key: 'vehicleWeapons',
                titleKey: 'tables.vehicleWeapons.title',
                color: colors.neons.orange.default,
                columns: [
                    { headerKey: 'headers.weapon' },
                    { headerKey: 'headers.damage', align: 'center' },
                    { headerKey: 'headers.rof', align: 'center' },
                    { headerKey: 'headers.cost', align: 'center' },
                ],
                rows: [
                    { cells: ['t:vehicles.vehicleMachineGun', '5d6', 1, '500 eb'] },
                    { cells: ['t:vehicles.vehicleMissileLauncher', '8d6', 1, '1000 eb'] },
                    { cells: ['t:vehicles.vehicleFlamethrower', '6d6+fire', 1, '500 eb'] },
                    { cells: ['t:vehicles.caltrops', '-', '-', '100 eb'] },
                ],
            },
            {
                key: 'vehicleCombatModifiers',
                titleKey: 'tables.vehicleCombatModifiers.title',
                color: colors.neons.orange.default,
                columns: [
                    { headerKey: 'headers.situation', width: '40%' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: ['t:vehicles.targetMovingFast', 't:vehicles.targetMovingFastEffect'] },
                    { cells: ['t:vehicles.vehicleMovingFast', 't:vehicles.vehicleMovingFastEffect'] },
                    { cells: ['t:vehicles.ram', 't:vehicles.ramEffect'] },
                    { cells: ['t:vehicles.sideswipe', 't:vehicles.sideswipeEffect'] },
                ],
            },
            {
                key: 'vehicleManeuverDVs',
                titleKey: 'tables.vehicleManeuverDVs.title',
                color: colors.neons.orange.default,
                columns: [
                    { headerKey: 'headers.maneuver', width: '50%' },
                    { headerKey: 'headers.dv', align: 'center' },
                ],
                rows: [
                    { cells: ['t:vehicles.simpleTurn', 9] },
                    { cells: ['t:vehicles.sharpTurn', 13] },
                    { cells: ['t:vehicles.bootleggerReverse', 15] },
                    { cells: ['t:vehicles.jumpObstacle', 15] },
                    { cells: ['t:vehicles.threadTraffic', 13] },
                    { cells: ['t:vehicles.avoidHazard', 13] },
                    { cells: ['t:vehicles.ramManeuver', 13] },
                ],
            },
        ],
    },
    // ─── CATEGORY 10: CHARACTER (PURPLE) ───
    {
        key: 'character',
        titleKey: 'categories.character',
        color: colors.neons.purple.default,
        tables: [
            {
                key: 'roleAbilities',
                titleKey: 'tables.roleAbilities.title',
                color: colors.neons.purple.default,
                columns: [
                    { headerKey: 'headers.role', width: '15%' },
                    { headerKey: 'headers.ability', width: '25%' },
                    { headerKey: 'headers.description' },
                ],
                rows: [
                    { cells: ['Rockerboy', 't:character.charismaticImpact', 't:character.charismaticImpactDesc'] },
                    { cells: ['Solo', 't:character.combatAwareness', 't:character.combatAwarenessDesc'] },
                    { cells: ['Netrunner', 't:character.interfaceAbility', 't:character.interfaceAbilityDesc'] },
                    { cells: ['Tech', 't:character.maker', 't:character.makerDesc'] },
                    { cells: ['Medtech', 't:character.medicine', 't:character.medicineDesc'] },
                    { cells: ['Media', 't:character.credibility', 't:character.credibilityDesc'] },
                    { cells: ['Exec', 't:character.teamwork', 't:character.teamworkDesc'] },
                    { cells: ['Lawman', 't:character.backup', 't:character.backupDesc'] },
                    { cells: ['Fixer', 't:character.operator', 't:character.operatorDesc'] },
                    { cells: ['Nomad', 't:character.moto', 't:character.motoDesc'] },
                ],
            },
            {
                key: 'ipCosts',
                titleKey: 'tables.ipCosts.title',
                color: colors.neons.purple.default,
                columns: [
                    { headerKey: 'headers.level', align: 'center' },
                    { headerKey: 'headers.normalSkill', align: 'center' },
                    { headerKey: 'headers.difficultSkill', align: 'center' },
                    { headerKey: 'headers.roleAbility', align: 'center' },
                ],
                rows: [
                    { cells: [1, 20, 40, 60] },
                    { cells: [2, 40, 80, 120] },
                    { cells: [3, 60, 120, 180] },
                    { cells: [4, 80, 160, 240] },
                    { cells: [5, 100, 200, 300] },
                    { cells: [6, 120, 240, 360] },
                    { cells: [7, 140, 280, 420] },
                    { cells: [8, 160, 320, 480] },
                    { cells: [9, 180, 360, 540] },
                    { cells: [10, 200, 400, 600], highlight: true },
                ],
            },
            {
                key: 'reputationEffects',
                titleKey: 'tables.reputationEffects.title',
                color: colors.neons.purple.default,
                columns: [
                    { headerKey: 'headers.rep', align: 'center', width: '15%' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: [0, 't:character.rep0'] },
                    { cells: ['1-2', 't:character.rep1_2'] },
                    { cells: ['3-4', 't:character.rep3_4'] },
                    { cells: ['5-6', 't:character.rep5_6'] },
                    { cells: ['7-8', 't:character.rep7_8'] },
                    { cells: ['9-10', 't:character.rep9_10'], highlight: true },
                ],
            },
            {
                key: 'humanityLossByType',
                titleKey: 'tables.humanityLossByType.title',
                color: colors.neons.purple.default,
                columns: [
                    { headerKey: 'headers.cyberwareType', width: '40%' },
                    { headerKey: 'headers.hlRange', align: 'center' },
                ],
                rows: [
                    { cells: ['t:character.fashionwareType', '0'] },
                    { cells: ['t:character.neuralwareType', '7-14'] },
                    { cells: ['t:character.cyberopticsType', '2-7'] },
                    { cells: ['t:character.cyberaudioType', '3-7'] },
                    { cells: ['t:character.internalCyberType', '2-14'] },
                    { cells: ['t:character.externalCyberType', '3-14'] },
                    { cells: ['t:character.cyberlimbsType', '2-7'] },
                    { cells: ['t:character.borgwareType', '14'], highlight: true },
                ],
            },
        ],
    },
    // ─── CATEGORY 11: MEDICAL & TECH (GREEN) ───
    {
        key: 'medicalTech',
        titleKey: 'categories.medicalTech',
        color: colors.neons.green.default,
        tables: [
            {
                key: 'firstAidDVs',
                titleKey: 'tables.firstAidDVs.title',
                color: colors.neons.green.default,
                columns: [
                    { headerKey: 'headers.condition', width: '30%' },
                    { headerKey: 'headers.skill', width: '20%' },
                    { headerKey: 'headers.dv', align: 'center', width: '15%' },
                    { headerKey: 'headers.effect' },
                ],
                rows: [
                    { cells: ['t:medical.lightlyWounded', 't:medical.firstAid', 13, 't:medical.heals2HP'] },
                    { cells: ['t:medical.seriouslyWounded', 't:medical.paramedic', 15, 't:medical.stabilizeHeal4HP'] },
                    { cells: ['t:medical.mortallyWounded', 't:medical.paramedic', 17, 't:medical.stabilizeOnly'] },
                    { cells: ['t:medical.critInjuryMinor', 't:medical.surgery', 15, 't:medical.critMinorEffect'] },
                    { cells: ['t:medical.critInjuryMajor', 't:medical.surgery', 17, 't:medical.critMajorEffect'] },
                ],
            },
            {
                key: 'surgeryDVs',
                titleKey: 'tables.surgeryDVs.title',
                color: colors.neons.green.default,
                columns: [
                    { headerKey: 'headers.procedure', width: '30%' },
                    { headerKey: 'headers.dv', align: 'center', width: '12%' },
                    { headerKey: 'headers.facility', width: '15%' },
                    { headerKey: 'headers.cost', align: 'center', width: '15%' },
                ],
                rows: [
                    { cells: ['t:medical.installFashionware', '-', 't:medical.mall', 't:common.free'] },
                    { cells: ['t:medical.installNeuralware', 15, 't:medical.clinic', '500 eb'] },
                    { cells: ['t:medical.installCyberoptics', 13, 't:medical.clinic', '500 eb'] },
                    { cells: ['t:medical.installCyberaudio', 13, 't:medical.clinic', '500 eb'] },
                    { cells: ['t:medical.installInternalCyber', 15, 't:medical.clinic', '500 eb'] },
                    { cells: ['t:medical.installExternalCyber', 15, 't:medical.clinic', '500 eb'] },
                    { cells: ['t:medical.installCyberlimbs', 17, 't:medical.hospital', '1000 eb'] },
                    { cells: ['t:medical.installBorgware', 17, 't:medical.hospital', '2500 eb'] },
                    { cells: ['t:medical.treatCritInjury', '15-17', '-', '-'] },
                ],
            },
            {
                key: 'installationCosts',
                titleKey: 'tables.installationCosts.title',
                color: colors.neons.green.default,
                columns: [
                    { headerKey: 'headers.facility', width: '20%' },
                    { headerKey: 'headers.cost', align: 'center', width: '15%' },
                    { headerKey: 'headers.notes' },
                ],
                rows: [
                    { cells: ['t:medical.mall', '100 eb', 't:medical.mallNotes'] },
                    { cells: ['t:medical.clinic', '500 eb', 't:medical.clinicNotes'] },
                    { cells: ['t:medical.hospital', '1000 eb', 't:medical.hospitalNotes'] },
                    { cells: ['t:medical.ripperdoc', '500 eb', 't:medical.ripperdocNotes'] },
                ],
            },
            {
                key: 'therapyDVs',
                titleKey: 'tables.therapyDVs.title',
                color: colors.neons.green.default,
                columns: [
                    { headerKey: 'headers.therapyType' },
                    { headerKey: 'headers.cost', align: 'center', width: '15%' },
                    { headerKey: 'headers.humanityRestored', align: 'center', width: '15%' },
                    { headerKey: 'headers.dv', align: 'center', width: '10%' },
                ],
                rows: [
                    { cells: ['t:medical.talkTherapy', '100 eb', '2d6', 15] },
                    { cells: ['t:medical.pharmaceuticalTherapy', '500 eb', '4d6', 17] },
                    { cells: ['t:medical.intensiveTherapy', '1000 eb', '6d6', 19] },
                ],
            },
            {
                key: 'drugEffects',
                titleKey: 'tables.drugEffects.title',
                color: colors.neons.green.default,
                columns: [
                    { headerKey: 'headers.drug' },
                    { headerKey: 'headers.cost', align: 'center', width: '12%' },
                    { headerKey: 'headers.effect' },
                    { headerKey: 'headers.addiction', width: '18%' },
                ],
                rows: [
                    { cells: ['t:medical.blackLace', '50 eb', 't:medical.blackLaceEffect', 't:medical.seriouslyAddictive'], highlight: true },
                    { cells: ['t:medical.blueGlass', '20 eb', 't:medical.blueGlassEffect', 't:medical.mildAddiction'] },
                    { cells: ['t:medical.boost', '50 eb', 't:medical.boostEffect', 't:medical.mildAddiction'] },
                    { cells: ['t:medical.smash', '10 eb', 't:medical.smashEffect', 't:medical.seriouslyAddictive'], highlight: true },
                    { cells: ['t:medical.synthcoke', '20 eb', 't:medical.synthcokeEffect', 't:medical.mildAddiction'] },
                    { cells: ['t:medical.timewarp', '100 eb', 't:medical.timewarpEffect', 't:medical.seriouslyAddictive'], highlight: true },
                ],
            },
        ],
    },
]
