enum GangType {
  MILITARY
  SYNDICATE
  BOOSTER
  GUARDIAN_VIGILANTE
  FREELANCER
  YO
  PRANKSTER
  RELIGIOUS
  EDGERUNNER
  POSER
}

enum CyberwareQuality {
  POOR
  STANDARD
  EXCELLENT
}

enum GangStatus {
  IGNORED_BY_ALL
  VASSAL
  INTEGRATED_WITH_NEIGHBORS
  STABLE_TRUCE
  SHAKY_TRUCE
  TURF_CONFLICT_TWO_SIDED
  TURF_CONFLICT_MULTI_SIDED
  CIVIL_WAR
  OUTSIDERS_INFILTRATED
  HUNTED_BY_ALL
}

enum GangColor {
  BLACK
  WHITE
  RED
  ORANGE
  YELLOW
  GREEN
  BLUE
  VIOLET
  BRIGHTS
  BROWNS
}

enum GangNameType {
  WEATHER_PHENOMENA
  COLOR
  PLACE
  WEAPON
  BODY_PART
  NUMBER
  ADJECTIVE
  PROFESSION
  ANIMAL
  NEIGHBORHOOD
}

enum Sin {
  LUST
  GLUTTONY
  GREED
  SLOTH
  WRATH
  ENVY
  PRIDE
  NONE
}

enum KnownForPart1 {
  HUGE
  SMALL
  EXPENSIVE
  CHEAP
  LUXURIOUS
  SHADY
  HOT
  COLD
  OVERRATED
  LOCAL
}

enum KnownForPart2 {
  EQUIPMENT
  RECRUITS
  WEAPONS
  TURF
  HQ
  BUDGET
  VEHICLES
  ATTITUDE
  EGO
  BELIEVES
}

enum Flaw {
  LACKLUSTER_LEADERSHIP
  DRUG_ADDICTS
  DEBT_LACK_OF_INCOME
  LACK_OF_RECRUITS
  AMMO_WEAPON_SHORTAGE
  NAIVE
  ILLITERATE_UNEDUCATED
  INEXPERIENCED_NEGOTIATORS
  NONE
}

enum Attitude {
  FOCUSED_ON_SOMETHING_ELSE
  FEARFUL
  INFIGHTING
  PLANNING
  PROVISIONING
  ROBBING_ASSAULTING
  BRIBING
  PARTING
  AGGRESSIVE
  NONE
}

enum GangNews {
  POLICE_COMING
  TEAM_RELEASED
  LAB_STASH_ROBBED
  NEW_ENEMY
  GAINED_TERRITORY
  BEING_SABOTAGED
  COP_RAIDING
  JOB_BLEW_UP
  NONE
}
