import { BuildingOwnership, BuildingStyle, BuildingType, GangNameType, GangType } from '../../graphql/types'
import { getRandomElement } from '../functions'
import { NameComponents } from '../types'

// Hugging Face constants
export const TEXT_MODEL_URL = 'https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.1' // Or your preferred HF text model
export const IMAGE_MODEL_URL = 'https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-xl-base-1.0' // Or your preferred HF image model

// Text generation types
export enum TextGenerationType {
    DESCRIPTION = 'description',
    NAME = 'name',
}

// ========================
// GANG NAME GENERATOR CONSTANTS
// ========================

// Gang name components by category
export const gangNameCategories: Record<GangNameType, string[]> = {
    [GangNameType.WEATHER_PHENOMENA]: [
        'Storm',
        'Thunder',
        'Lightning',
        'Hurricane',
        'Cyclone',
        'Blizzard',
        'Tornado',
        'Tempest',
        'Haze',
        'Fog',
        'Mist',
        'Rain',
        'Typhoon',
        'Smog',
        'Ash',
        'Inferno',
        'Dust',
        'Shock',
        'Sand',
        'Gale',
    ],
    [GangNameType.COLOR]: [
        'Crimson',
        'Neon',
        'Obsidian',
        'Chrome',
        'Indigo',
        'Violet',
        'Scarlet',
        'Ivory',
        'Cobalt',
        'Amber',
        'Emerald',
        'Onyx',
        'Azure',
        'Neochrome',
        'Silver',
        'Gold',
        'Copper',
        'Jade',
        'Ultraviolet',
        'Infrared',
    ],
    [GangNameType.PLACE]: [
        'Sector',
        'District',
        'Zone',
        'Hive',
        'Harbor',
        'Alley',
        'Bay',
        'Gate',
        'Sprawl',
        'Dock',
        'Underground',
        'Metro',
        'Megaplex',
        'Grid',
        'Complex',
        'Streets',
        'Core',
        'Wastes',
        'Arena',
        'Den',
    ],
    [GangNameType.WEAPON]: [
        'Blades',
        'Guns',
        'Razors',
        'Lasers',
        'Knives',
        'Rifles',
        'Bullets',
        'Daggers',
        'Axes',
        'Sabers',
        'Chains',
        'Shurikens',
        'Gauntlets',
        'Swords',
        'Pistols',
        'Cannons',
        'Railguns',
        'Arsenal',
        'Spikes',
        'Hammers',
    ],
    [GangNameType.BODY_PART]: [
        'Eyes',
        'Claws',
        'Fangs',
        'Hearts',
        'Hands',
        'Spines',
        'Skulls',
        'Veins',
        'Fists',
        'Jaws',
        'Bones',
        'Talons',
        'Knuckles',
        'Nerves',
        'Skin',
        'Muscle',
        'Blood',
        'Breath',
        'Minds',
        'Fang',
    ],
    [GangNameType.NUMBER]: [
        'Eight',
        'Sixteen',
        'Eighteen',
        'Twenty-Three',
        'Twenty-Seven',
        'Thirty-Two',
        'Thirty-Five',
        'Forty-Two',
        'Forty-Four',
        'Fifty-Three',
        'Fifty-Eight',
        'Sixty-Four',
        'Sixty-Nine',
        'Seventy-Two',
        'Eighty-One',
        'Ninety-Nine',
        'Hundred',
        'Thousand',
        'Zero',
        'Million',
    ],
    [GangNameType.ADJECTIVE]: [
        'Cyber',
        'Savage',
        'Digital',
        'Phantom',
        'Grim',
        'Iron',
        'Quantum',
        'Synthetic',
        'Virtual',
        'Rogue',
        'Neural',
        'Augmented',
        'Chromed',
        'Dystopian',
        'Radical',
        'Atomic',
        'Genetic',
        'Infamous',
        'Encrypted',
        'Toxic',
    ],
    [GangNameType.PROFESSION]: [
        'Nomads',
        'Hackers',
        'Runners',
        'Fixers',
        'Mercs',
        'Techs',
        'Netrunners',
        'Scavengers',
        'Rippers',
        'Mechanics',
        'Slicers',
        'Boosters',
        'Ronin',
        'Operatives',
        'Smugglers',
        'Hunters',
        'Dealers',
        'Enforcers',
        'Engineers',
        'Ghosts',
    ],
    [GangNameType.ANIMAL]: [
        'Wolves',
        'Ravens',
        'Jackals',
        'Sharks',
        'Vipers',
        'Cobras',
        'Panthers',
        'Falcons',
        'Rats',
        'Hornets',
        'Spiders',
        'Scorpions',
        'Wasps',
        'Hyenas',
        'Bats',
        'Mantis',
        'Serpents',
        'Leopards',
        'Locusts',
        'Dragons',
    ],
    [GangNameType.NEIGHBORHOOD]: [
        'Watson',
        'Pacifica',
        'Kabuki',
        'Chinatown',
        'Charter',
        'Heywood',
        'Glen',
        'Japantown',
        'Coronado',
        'Santo',
        'Westbrook',
        'Vista',
        'Arroyo',
        'Plaza',
        'Northside',
        'Combat',
        'Industrial',
        'University',
        'Southside',
        'Badlands',
    ],
}

// Additional components for gang names
export const gangSuffixes = [
    'Crew',
    'Gang',
    'Posse',
    'Squad',
    'Pack',
    'Clan',
    'Family',
    'Brotherhood',
    'Syndicate',
    'Cartel',
    'Mafia',
    'Collective',
    'Network',
    'Legion',
    'Tribe',
    'Coalition',
    'Ring',
    'Outfit',
    'Faction',
    'Union',
]

export const gangPrefixes = [
    'Los',
    'Las',
    'The',
    'Cyber',
    'Neo',
    'Night',
    'Street',
    'Urban',
    'Metro',
    'Wild',
    'Rogue',
    'Shadow',
    'Neon',
    'Chrome',
    'Midnight',
    'Steel',
    'Digital',
    'Terminal',
    'Tech',
    'Primal',
]

export const gangConnectors = [
    'of',
    'from',
    'in',
    'of the',
    'from the',
    'against',
    'beyond',
    'under',
    'over',
    'against the',
    'beyond the',
]

// Preferred naming patterns for different gang types
export const gangTypeNameData: Record<GangType, { preferredPatterns: number[] }> = {
    [GangType.BOOSTER]: {
        preferredPatterns: [1, 2, 4, 6, 7, 10],
    },
    [GangType.EDGERUNNER]: {
        preferredPatterns: [3, 5, 9, 11, 12],
    },
    [GangType.FREELANCER]: {
        preferredPatterns: [1, 4, 5, 8, 10],
    },
    [GangType.GUARDIAN_VIGILANTE]: {
        preferredPatterns: [3, 7, 9, 11, 14],
    },
    [GangType.MILITARY]: {
        preferredPatterns: [2, 6, 8, 13, 14],
    },
    [GangType.POSER]: {
        preferredPatterns: [1, 4, 5, 10, 15],
    },
    [GangType.PRANKSTER]: {
        preferredPatterns: [4, 5, 10, 12, 15],
    },
    [GangType.RELIGIOUS]: {
        preferredPatterns: [3, 7, 9, 13, 14],
    },
    [GangType.SYNDICATE]: {
        preferredPatterns: [2, 6, 8, 9, 13],
    },
    [GangType.YO]: {
        preferredPatterns: [1, 4, 10, 12, 15],
    },
}

// ========================
// BUILDING NAME GENERATOR CONSTANTS
// ========================

// Corporate prefixes for corporate buildings
export const corpoPrefixes = [
    'Arasaka',
    'Militech',
    'Biotechnica',
    'Petrochem',
    'Kang Tao',
    'Zetatech',
    'Night Corp',
    'Budget Arms',
    'Trauma Team',
    'Dynalar',
    'Orbital Air',
    'Lazarus Group',
    'Kiroshi Optics',
    'SovOil',
    'Infocomp',
    'Delamain',
    'EBM Holdings',
    'Kendachi Industries',
    'NeoNet',
    'MicroTech',
    'Nakamura Engineering',
    'WorldSat Communications',
]

// Building suffixes (common for all building types)
export const buildingSuffixes = [
    'Plaza',
    'Tower',
    'Center',
    'Building',
    'Complex',
    'Nexus',
    'Block',
    'Heights',
    'Arcade',
    'Station',
    'Chambers',
    'Sanctuary',
    'Quarters',
    'Haven',
    'House',
    'Depot',
    'Point',
    'Square',
    'Lofts',
    'Facility',
]

// District names for location context
export const districtNames = [
    'Watson',
    'Westbrook',
    'Heywood',
    'Santo Domingo',
    'Pacifica',
    'City Center',
    'Northside',
    'Little China',
    'Kabuki',
    'Charter Hill',
    'North Oak',
    'Japantown',
    'Arroyo',
    'Wellsprings',
    'Vista Del Rey',
    'Rancho Coronado',
    'Glen',
    'The Glen',
    'Coastview',
    'West Wind',
    'Red Light District',
    'Industrial Zone',
]

// Street suffixes for address-style names
export const streetSuffixes = [
    'Street',
    'Avenue',
    'Boulevard',
    'Lane',
    'Drive',
    'Way',
    'Place',
    'Road',
    'Court',
    'Alley',
    'Circle',
    'Highway',
    'Parkway',
    'Crescent',
    'Expressway',
    'Bridge',
    'Walk',
    'District',
]

// Landmark prefixes for various naming styles
export const landmarkPrefixes = [
    'Old',
    'New',
    'Eastern',
    'Western',
    'Northern',
    'Southern',
    'Upper',
    'Lower',
    'Central',
    'Downtown',
    'Uptown',
    'Neo',
    'Cyber',
    'Metro',
    'Greater',
    'Inner',
    'Outer',
    'Mid',
]

// Surnames for possessive naming patterns
export const surnames = [
    'Rodriguez',
    'Smith',
    'Jensen',
    'Wang',
    'Takemura',
    'Singh',
    'Coleman',
    'Ortega',
    'Freeman',
    'Martinez',
    'Chang',
    'Blackhand',
    'Silverhand',
    'Weyland',
    'Parker',
    'Kovacs',
    'Deckard',
    'Chen',
    'Kim',
    'Tanaka',
    'Nakamura',
    'Gonzalez',
    'Chiba',
    'Kennedy',
    'Yakamoto',
    'Yamane',
    'Patel',
    'Ivanov',
    'Kovalsky',
    "O'Neill",
    'Morgan',
    'Jackson',
    'Kowalski',
    'Lee',
    'Wong',
    'Nguyen',
    'Russo',
    'Esposito',
    'Rossi',
    'Dubois',
    'Schmidt',
    'Malhotra',
    'Gupta',
    'Sato',
    'Suzuki',
    'Yamamoto',
    'Yamaguchi',
]

// Compound name components
export const compoundPrefixes = [
    'Neo',
    'Meta',
    'Mega',
    'Cyber',
    'Tech',
    'Digi',
    'Syn',
    'Virt',
    'Hyper',
    'Ultra',
    'Max',
    'Prime',
    'Omni',
    'Trans',
    'Nova',
    'Quantum',
    'Nexus',
    'Fusion',
    'Vector',
    'Pixel',
]

export const compoundSuffixes = [
    'tronics',
    'systems',
    'corporation',
    'tech',
    'soft',
    'dyne',
    'ware',
    'works',
    'net',
    'plex',
    'tec',
    'com',
    'sync',
    'gen',
    'hub',
    'sphere',
    'grid',
    'matrix',
    'link',
    'node',
]

// Common name elements
export const commonNameElements = {
    // Location elements
    districtNames,
    streetSuffixes,
    landmarkPrefixes,

    // Building elements
    buildingSuffixes,
    corpoPrefixes,

    // Name components
    surnames,
    compoundPrefixes,
    compoundSuffixes,
}

// Unified structure for styling and naming
export const buildingNameData: Record<BuildingType | BuildingStyle | BuildingOwnership, Partial<NameComponents>> = {
    // Building Types
    [BuildingType.ABANDONED_BUILDING]: {
        buildingTypeWords: [
            'Abandoned',
            'Derelict',
            'Empty',
            'Deserted',
            'Vacant',
            'Decaying',
            'Former',
            'Ruined',
            'Condemned',
            'Forgotten',
            'Dilapidated',
            'Neglected',
            'Shuttered',
            'Disused',
            'Forsaken',
            'Deteriorated',
            'Collapsed',
            'Crumbling',
            'Degraded',
            'Ghost',
            'Vestigial',
            'Hollow',
        ],
        preferredPatterns: [1, 6, 8, 12],
    },
    [BuildingType.COMMERCIAL_BUILDING]: {
        buildingTypeWords: [
            'Business',
            'Commercial',
            'Trade',
            'Retail',
            'Market',
            'Merchant',
            'Shopping',
            'Exchange',
            'Mall',
            'Emporium',
            'Bazaar',
            'Mart',
            'Outlet',
            'Center',
            'Arcade',
            'Store',
            'Boutique',
            'Marketplace',
            'Galleria',
            'Shophouse',
            'Megastore',
            'Hypermarket',
            'Megamall',
            'Depot',
            'Warehouse',
            'Showroom',
            'Pavilion',
            'Atrium',
            'Trading Post',
            'Floorspace',
        ],
        preferredPatterns: [1, 2, 3, 8, 8, 8, 9],
    },
    [BuildingType.CORPO_BUILDING]: {
        buildingTypeWords: [
            'Corporate',
            'Company',
            'Enterprise',
            'Firm',
            'Agency',
            'Bureau',
            'Office',
            'Headquarters',
            'HQ',
            'Branch',
            'Division',
            'Department',
            'Center',
            'Wing',
            'Annex',
            'Sector',
            'Section',
            'Complex',
            'Suite',
            'Campus',
            'Operations',
            'Facility',
            'Installation',
            'Outpost',
        ],
        preferredPatterns: [2, 7, 9, 10],
        corpoAffiliation: true,
    },
    [BuildingType.CUBE_HOTEL_MOTEL_CARGO_CONTAINER]: {
        buildingTypeWords: [
            'Cube',
            'Container',
            'Pod',
            'Capsule',
            'Coffin',
            'Compact',
            'Micro',
            'Cell',
            'Motel',
            'Hotel',
            'Inn',
            'Lodge',
            'Housing',
            'Quarters',
            'Dormitory',
            'Bunkhouse',
            'Hostel',
            'Sleep Box',
            'Stacker',
            'Hive',
            'Stack',
            'Nest',
            'Honeycomb',
            'Module',
            'Crate',
            'Cabin',
            'Berth',
            'Rest Stop',
            'Sleep Center',
            'Crash Pad',
        ],
        preferredPatterns: [4, 5, 8, 10],
    },
    [BuildingType.ESTABLISHMENT]: {
        buildingTypeWords: [
            'Private Club',
            'Braindance',
            'Foundation',
            'Gang Club',
            'Concern',
            'Operation',
            'House',
            'Outlet',
            'Bodega',
            'Dance Club',
            'Garage',
            'Bar',
            'Restaurant',
            'Diner',
            'Café',
            'Store',
            'Shop',
            'Lounge',
            'Parlor',
            'Pub',
            'Tavern',
            'Eatery',
            'Striptease',
            'Chophouse',
            'Nightclub',
            'Speakeasy',
            'Bistro',
            'Autoservice',
            'Workshop',
            'Brothel',
            'Salon',
            'Laundromat',
            'Pharmacy',
            'Booth',
            'Stand',
            'Kiosk',
            'Corner Store',
        ],
        preferredPatterns: [1, 3, 7, 8, 8, 8, 11],
    },
    [BuildingType.GOV_BUILDING]: {
        buildingTypeWords: [
            'Government',
            'Municipal',
            'Administrative',
            'Civic',
            'Public',
            'Official',
            'State',
            'Federal',
            'Police',
            'Department',
            'Precinct',
            'Agency',
            'Bureau',
            'Authority',
            'Commission',
            'PD',
            'IRS',
            'NSA',
            'CIA',
            'FBI',
            'Courthouse',
            'City Hall',
            'Ministry',
            'Regulatory',
            'Control',
            'Enforcement',
            'Inspection',
            'Security',
            'Archive',
            'Registry',
            'Defense',
            'Justice',
            'Treasury',
            'Intelligence',
            'Headquarters',
            'Office',
            'Division',
        ],
        preferredPatterns: [1, 3, 6, 10],
    },
    [BuildingType.LUXURY_PENTHOUSE_MCMANSION]: {
        buildingTypeWords: [
            'Luxury',
            'Elite',
            'Premium',
            'Deluxe',
            'Prime',
            'Exclusive',
            'Prestige',
            'Executive',
            'Penthouse',
            'Mansion',
            'Estate',
            'Villa',
            'Palace',
            'Château',
            'Suite',
            'Residence',
            'Loft',
            'Condo',
            'Apartment',
            'Retreat',
            'Haven',
            'Sanctuary',
            'Manor',
            'Rooftop',
            'Skypad',
            'Atrium',
            'Oasis',
            'Resort',
            'Highrise',
            'Domain',
        ],
        preferredPatterns: [2, 7, 9, 11],
    },
    [BuildingType.MEGACORPO_HQ]: {
        buildingTypeWords: [
            'Megacorp',
            'Conglomerate',
            'Global',
            'Multinational',
            'Sovereign',
            'Dominant',
            'Monolith',
            'Empire',
            'Zaibatsu',
            'Corporate',
            'Nexus',
            'Citadel',
            'Fortress',
            'Colossus',
            'Leviathan',
            'Megalith',
            'Consortium',
            'Syndicate',
            'Institution',
            'World HQ',
            'Headquarters',
            'Central',
            'Command',
            'Arcology',
            'Domain',
            'Power Center',
            'World Office',
            'Pyramid',
            'Superstructure',
        ],
        preferredPatterns: [2, 7, 9],
        corpoAffiliation: true,
    },
    [BuildingType.MULTI_STORY_BUILDING]: {
        buildingTypeWords: [
            'Tower',
            'High-Rise',
            'Complex',
            'Block',
            'Stories',
            'Levels',
            'Multi-Floor',
            'Stack',
            'Mid-Rise',
            'Structure',
            'Building',
            'Stacked',
            'Construct',
            'Residence',
            'Apartments',
            'Housing',
            'Development',
            'Units',
            'Flats',
            'Elevation',
            'Habitat',
            'Highblock',
            'Tenement',
            'Rise',
            'Community',
            'Vertical',
            'Compound',
            'Height',
        ],
        preferredPatterns: [1, 3, 4, 5, 6, 10],
    },
    [BuildingType.PUBLIC_SPACE]: {
        buildingTypeWords: [
            'Plaza',
            'Commons',
            'Forum',
            'Square',
            'Park',
            'Ground',
            'Yard',
            'Court',
            'Station',
            'Street',
            'Road',
            'Boulevard',
            'Esplanade',
            'Promenade',
            'Garden',
            'Terminal',
            'Arcade',
            'Marketplace',
            'Concourse',
            'Atrium',
            'Quad',
            'Piazza',
            'Hub',
            'Terrace',
            'Platform',
            'Junction',
            'Crossing',
            'Metro',
            'Arena',
            'Mall',
            'Zone',
            'Corridor',
            'Transit',
            'Interchange',
            'Gallery',
            'Concourse',
            'Pavilion',
            'Center',
        ],
        preferredPatterns: [3, 5, 6, 11],
    },
    [BuildingType.SKYSCRAPER_MEGABUILDING]: {
        buildingTypeWords: [
            'Skyscraper',
            'Spire',
            'Colossus',
            'Megastructure',
            'Giant',
            'Behemoth',
            'Titan',
            'Vertical City',
            'Megabuilding',
            'Arcology',
            'Supertower',
            'Hyperstructure',
            'Monument',
            'Pinnacle',
            'Citadel',
            'Megalith',
            'Urban Mountain',
            'Cloud Piercer',
            'Stratosphere',
            'Superstructure',
            'Horizon',
            'Megacomplex',
            'Heaven Scraper',
            'Mega-Rise',
            'Superspire',
            'Ultratower',
            'Sky Needle',
        ],
        preferredPatterns: [1, 2, 3, 7, 9],
    },
    [BuildingType.VACANT_LOT_CONSTRUCTION_SITE]: {
        buildingTypeWords: [
            'Site',
            'Ground',
            'Zone',
            'Lot',
            'Plot',
            'Land',
            'Field',
            'Construction',
            'Development',
            'Project',
            'Property',
            'Area',
            'Territory',
            'Acreage',
            'Clearing',
            'Excavation',
            'Foundation',
            'Worksite',
            'Yard',
            'Unfinished',
            'Scaffold',
            'Incomplete',
            'Undeveloped',
            'Framework',
            'Skeleton',
            'Phase',
            'Venture',
            'Undertaking',
        ],
        preferredPatterns: [4, 5, 10, 12],
    },

    // Styles
    [BuildingStyle.AUSTERE]: {
        styleAdjectives: [
            'Austere',
            'Sparse',
            'Minimalist',
            'Plain',
            'Unadorned',
            'Frugal',
            'Bleak',
            'Simple',
            'Stark',
            'Utilitarian',
            'Functional',
            'Bare',
            'Essential',
            'Modest',
            'Restrained',
            'Stripped',
            'Barren',
            'Severe',
            'Practical',
            'Monastic',
            'Ascetic',
            'Unembellished',
        ],
        nameModifier: (name) => (name.includes('The') ? name : `${name.trim()}`),
    },
    [BuildingStyle.CORPORATE]: {
        styleAdjectives: [
            'Corporate',
            'Enterprise',
            'Executive',
            'Business',
            'Formal',
            'Streamlined',
            'Professional',
            'Regulated',
            'Commercial',
            'Official',
            'Managerial',
            'Administrative',
            'Institutional',
            'Bureaucratic',
            'Systematic',
            'Conventional',
            'Standardized',
            'Uniform',
            'Structured',
            'Procedural',
            'Pragmatic',
            'Efficient',
        ],
        nameModifier: (name, _typeWord, suffix) =>
            name.includes('Complex') || name.includes('Tower') ? name : `${name.trim()} ${suffix}`,
    },
    [BuildingStyle.EUROPEAN]: {
        styleAdjectives: [
            'European',
            'Continental',
            'Classic',
            'Old-World',
            'Baroque',
            'Renaissance',
            'Colonial',
            'Mediterranean',
        ],
        nameModifier: (name) => (name.includes('The') ? name : `The ${name.trim()}`),
    },
    [BuildingStyle.EXOTIC]: {
        styleAdjectives: ['Exotic', 'Unusual', 'Rare', 'Foreign', 'Alien', 'Mystical', 'Outlandish', 'Otherworldly'],
        nameModifier: (name) => name,
    },
    [BuildingStyle.LUXURIOUS]: {
        styleAdjectives: ['Luxurious', 'Opulent', 'Lavish', 'Extravagant', 'Deluxe', 'Sumptuous', 'Gilded', 'High-End'],
        nameModifier: (name) => (name.includes('Luxury') ? name : `Luxury ${name.trim()}`),
    },
    [BuildingStyle.MILITARISTIC]: {
        styleAdjectives: [
            'Militaristic',
            'Fortress',
            'Bunker',
            'Defense',
            'Tactical',
            'Armored',
            'Disciplined',
            'Regimental',
        ],
        nameModifier: (name) => (name.includes('Secure') ? name : `Secure ${name.trim()}`),
    },
    [BuildingStyle.MODERN]: {
        styleAdjectives: [
            'Modern',
            'Contemporary',
            'Current',
            'Progressive',
            'Futuristic',
            'Cutting-Edge',
            'Sleek',
            'Techno',
        ],
        nameModifier: (name) => name,
    },
    [BuildingStyle.NEON_FEST]: {
        styleAdjectives: [
            'Neon',
            'Glow',
            'Electric',
            'Luminous',
            'Iridescent',
            'Radiant',
            'Fluorescent',
            'Pulsing',
            'Vibrant',
            'Dazzling',
            'Glowing',
            'Flashing',
            'Bright',
            'Colorful',
            'Psychedelic',
            'Shimmering',
            'Blinding',
            'Gleaming',
            'Flaring',
            'Prismatic',
            'Laser',
            'Holographic',
            'Phosphorescent',
            'Chromatic',
        ],
        nameModifier: (name) => (name.includes('Neon') ? name : `Neon ${name.trim()}`),
    },
    [BuildingStyle.ORIENTAL]: {
        styleAdjectives: ['Oriental', 'Eastern', 'Zen', 'Dynasty', 'Lotus', 'Imperial', 'Silken', 'Meditative'],
        nameModifier: (name) => name,
    },
    [BuildingStyle.SOVIETIC]: {
        styleAdjectives: [
            'Soviet',
            'United',
            'Red',
            'Communist',
            'Hammer-and-Sickle',
            'Proletarian',
            "People's",
            'Industrialist',
        ],
        nameModifier: (name) => {
            // Process styleAdjectives to get simple terms (handling compound words and possessives)
            const terms = buildingNameData[BuildingStyle.SOVIETIC].styleAdjectives!.flatMap((adj) => {
                // Handle compound adjectives like "Hammer-and-Sickle"
                if (adj.includes('-')) {
                    return adj
                        .split(/[-\s]/)
                        .filter((part) => part !== 'and')
                        .map((part) => part.toLowerCase())
                }
                // Handle possessives
                return adj.replace("'s", '').toLowerCase()
            })

            // Add a few additional terms that might be in generated names
            terms.push('hammer', 'sickle')

            // Check if any term is already present in the name (case insensitive)
            const hasAnyTerm = terms.some((term) => name.toLowerCase().includes(term))

            // Only add "People's" if no related terms exist
            return hasAnyTerm ? name.trim() : `People's ${name.trim()}`
        },
    },
    [BuildingStyle.TRIBAL]: {
        styleAdjectives: [
            'Tribal',
            'Native',
            'Indigenous',
            'Ancestral',
            'Totemic',
            'Shamanic',
            'Nomadic',
            'Ceremonial',
        ],
        nameModifier: (name) => name,
    },
    [BuildingStyle.URBAN_GRAFFITI]: {
        styleAdjectives: ['Graffiti', 'Street', 'Urban', 'Tagged', 'Vandalized', 'Sprayed', 'Rebel', 'Concrete'],
        nameModifier: (name) => (name.includes('Street') ? name : `Street ${name.trim()}`),
    },

    // BuildingOwnership affects naming
    [BuildingOwnership.CORPO]: {
        corpoAffiliation: true,
    },
    [BuildingOwnership.MEGA_CORPO]: {
        corpoAffiliation: true,
    },
    [BuildingOwnership.BYSTANDER]: {},
    [BuildingOwnership.FIXER]: {},
    [BuildingOwnership.GANG_MAFIA]: {},
    [BuildingOwnership.GOVERNMENT]: {
        corpoAffiliation: false,
    },
    [BuildingOwnership.LOCAL_GOV]: {
        corpoAffiliation: false,
    },
    [BuildingOwnership.LOW_LEVEL_GONKS]: {},
    [BuildingOwnership.MILITARISTIC_GANG]: {},
    [BuildingOwnership.NO_ONE_SCAVS]: {},
    [BuildingOwnership.POSERGANG]: {},
    [BuildingOwnership.SMALL_BUSINESS]: {
        nameModifier: (name) => {
            // Small chance to add a second surname for family businesses
            const useTwoSurnames = Math.random() < 0.3
            if (useTwoSurnames && !name.includes("'s")) {
                const surname1 = getRandomElement(commonNameElements.surnames)
                const surname2 = getRandomElement(commonNameElements.surnames)
                return `${surname1} & ${surname2}${name.includes(' ') ? ' ' + name.split(' ').slice(1).join(' ') : ''}`
            }
            return name
        },
    },
}

// Storage keys used in the application for module data
// Note: User settings like view preferences and reader mode are deliberately excluded
export const APP_STORAGE_KEYS = [
    'magnus-laser-gangs',
    'magnus-laser-buildings',
    'magnus-laser-fixer-jobs',
    'magnus-laser-view-preferences',
    'magnus-laser-reader-mode',
    'magnus-laser-huggingface-api-key',
]

export const personNames = [
    'Adela',
    'Adele',
    'Aaliyah',
    'Ae-cha',
    'Abigail',
    'Alexandra',
    'Agnes',
    'Abra',
    'Aki',
    'Addison',
    'Alicja',
    'Aldith',
    'Alba',
    'Amala',
    'Agas',
    'Alina',
    'Amelia',
    'Amina',
    'Amaya',
    'Agnes',
    'Anna',
    'Anke',
    'Atara',
    'Asuka',
    'Ashley',
    'Aurelia',
    'Astrid',
    'Baako',
    'Atarah',
    'Aurora',
    'Beata',
    'Bertha',
    'Bailu',
    'Biao',
    'Bailey',
    'Berenike',
    'Betrine',
    'Basia',
    'Binita',
    'Beatrix',
    'Bianka',
    'Blanche',
    'Batya',
    'Bunko',
    'Benita',
    'Brygida',
    'Brina',
    'Binah',
    'Chae-won',
    'Bess',
    'Cecylia',
    'Camille',
    'Carnia',
    'Chao',
    'Bonita',
    'Ceren',
    'Carlyn',
    'Chanah',
    'Chieko',
    'Brook',
    'Danka',
    'Celestia',
    'Chaya',
    'Chimlin',
    'Cady',
    'Daphne',
    'Celine',
    'Dania',
    'Da-eun',
    'Caitlyn',
    'Delia',
    'Christia',
    'Davida',
    'Daiyu',
    'Candice',
    'Diana',
    'Ciara',
    'Degania',
    'Daksha',
    'Carla',
    'Dominika',
    'Clara',
    'Devora',
    'Eshana',
    'Carmen',
    'Dorota',
    'Clarisse',
    'Ecter',
    'Eun-jeong',
    'Casey',
    'Drina',
    'Clodette',
    'Eder',
    'Eun-ju',
    'Chleo',
    'Edyta',
    'Coraline',
    'Etna',
    'Eun-kyung',
    'Chloe',
    'Elena',
    'Dordi',
    'Eyphah',
    'Feng',
    'Daisy',
    'Emilia',
    'Ebbe',
    'Fahima',
    'Fuji',
    'Deana',
    'Ewa',
    'Edith',
    'Fatima',
    'Fumiko',
    'Deni',
    'Felicja',
    'Elisa',
    'Fidda',
    'Ga-ram',
    'Earline',
    'Fidan',
    'Elsa',
    'Folami',
    'Gayathri',
    'Eleonora',
    'Flora',
    'Federica',
    'Galia',
    'Gina',
    'Elizabeth',
    'Frida',
    'Finna',
    'Hadas',
    'Gteong-Hui',
    'Evita',
    'Gabriela',
    'Fiona',
    'Hadya',
    'Gulika',
    'Felicia',
    'Gaia',
    'Flavie',
    'Hania',
    'Gyeo-wool',
    'Filipa',
    'Hagne',
    'Fleur',
    'Hanifa',
    'Ha-yun',
    'Frea',
    'Halka',
    'Frauke',
    'Hant',
    'Hana',
    'Georgia',
    'Hanna',
    'Frida',
    'Hasida',
    'Hanako',
    'Gloria',
    'Hestia',
    'Hedwig',
    'Henya',
    'Hao',
    'Gwen',
    'Ida',
    'Helga',
    'Ilama',
    'Haru',
    'Harley',
    'Ionna',
    'Helma',
    'Inbal',
    'Harumi',
    'Harmony',
    'Irena',
    'Hilde',
    'Irit',
    'Hikari',
    'Haylee',
    'Iris',
    'Holle',
    'Ismat',
    'Himig',
    'Holy',
    'Iwona',
    'Ilma',
    'Jaffe',
    'Hwan',
    'India',
    'Izabela',
    'Imelda',
    'Jamila',
    'Hye-jin',
    'Jackie',
    'Janka',
    'Inger',
    'Jeleh',
    'Idika',
    'Jade',
    'Joanna',
    'Ingrid',
    'Jumanah',
    'Iseul',
    'Jasmin',
    'Jola',
    'Irma',
    'Kalanit',
    'Izumi',
    'Jessica',
    'Jowita',
    'Isane',
    'Karima',
    'Jeong-sku',
    'Joana',
    'Kalliope',
    'Isold',
    'Karmel',
    'Ji-min',
    'Josefina',
    'Kamila',
    'Jolie',
    'Karnia',
    'Jiao',
    'Juana',
    'Karme',
    'Juliane',
    'Keshet',
    'Junko',
    'Julie',
    'Karolina',
    'Jutte',
    'Lafita',
    'Kameko',
    'Kaelee',
    'Kasandra',
    'Kine',
    'Levi',
    'Kamuri',
    'Kath',
    'Katarzyna',
    'Klara',
    'Liat',
    'Kasumi',
    'Kolleen',
    'Katerina',
    'Laga',
    'Liba',
    'Kazumi',
    'Lacie',
    'Kizzy',
    'Laila',
    'Lilith',
    'Kim',
    'Linda',
    'Klara',
    'Lilia',
    'Lubna',
    'Kiyoko',
    'Linsay',
    'Klaudia',
    'Liv',
    'Maria',
    'Krisha',
    'Lola',
    'Kora',
    'Lora',
    'Marva',
    'Lamai',
    'Louanna',
    'Kornelia',
    'Lorenza',
    'Medea',
    'Lekha',
    'Lucinda',
    'Lamia',
    'Lotte',
    'Mesta',
    'Li',
    'Luiza',
    'Laura',
    'Luise',
    'Naamiy',
    'Lien',
    'Lupe',
    'Lena',
    'Maddie',
    'Nahala',
    'Liling',
    'Mable',
    'Lidia',
    'Mona',
    'Nasreen',
    'Ma-ri',
    'Makayla',
    'Ludmilla',
    'Monique',
    'Nessa',
    'Madoka',
    'Malina',
    'Lydia',
    'Nala',
    'Nurya',
    'Mahika',
    'Margaret',
    'Łucja',
    'Nerina',
    'Ophrah',
    'Maiko',
    'Misty',
    'Magda',
    'Norene',
    'Oralee',
    'Malaya',
    'Monica',
    'Maja',
    'Odilia',
    'Ornat',
    'Masako',
    'Nell',
    'Marta',
    'Ornella',
    'Parvana',
    'Masami',
    'Nina',
    'Melania',
    'Ottilie',
    'Pauline',
    'Megumi',
    'Nora',
    'Melite',
    'Paola',
    'Peninnah',
    'Meili',
    'Nubia',
    'Milena',
    'Perrine',
    'Pili',
    'Ming',
    'Octavia',
    'Nadia',
    'Piera',
    'Rafaela',
    'Moriko',
    'Pamela',
    'Nadzieja',
    'Prima',
    'Ramla',
    'Na-ree',
    'Patricia',
    'Natalia',
    'Rebecca',
    'Ranno',
    'Neomi',
    'Petra',
    'Natasha',
    'Regina',
    'Rasima',
    'Nobuko',
    'Phoebe',
    'Nora',
    'Reine',
    'Reva',
    'Nori',
    'Piper',
    'Nuray',
    'Renate',
    'Rina',
    'Nyra',
    'Priscila',
    'Nyx',
    'Riva',
    'Safita',
    'Perlah',
    'Rachel',
    'Oksana',
    'Rosaria',
    'Salia',
    'Phailin',
    'Rafaela',
    'Oliwia',
    'Rosette',
    'Sambra',
    'Reiko',
    'Raquel',
    'Ophelia',
    'Rosine',
    'Samia',
    'Rin',
    'Rebeca',
    'Patrycja',
    'Runa',
    'Saray',
    'Saira',
    'Reilly',
    'Pelagia',
    'Sabine',
    'Selina',
    'Seo-Yeon',
    'Rita',
    'Persis',
    'Samuela',
    'Shamira',
    'Seung-wan',
    'Samantha',
    'Rheia',
    'Sandra',
    'Shani',
    'Shu',
    'Sarita',
    'Roksana',
    'Selma',
    'Shifra',
    'Shura',
    'Scarlett',
    'Róża',
    'Shanon',
    'Shirin',
    'Su-bin',
    'Selby',
    'Ruta',
    'Sigi',
    'Shula',
    'Sunita',
    'Sheila',
    'Sanaz',
    'Signe',
    'Sigal',
    'Suzume',
    'Sky',
    'Sara',
    'Sigyn',
    'Tahirah',
    'Takako',
    'Sophia',
    'Selene',
    'Stephane',
    'Tamara',
    'Thuy',
    'Stacy',
    'Sylwia',
    'Susana',
    'Temeka',
    'Tomoko',
    'Storm',
    'Tekla',
    'Svana',
    'Themba',
    'Turvi',
    'Summer',
    'Thea',
    'Theresa',
    'Thia',
    'Umeko',
    'Tamara',
    'Tuija',
    'Tonia',
    'Tothia',
    'Usha',
    'Taylor',
    'Tyro',
    'Tonje',
    'Urith',
    'Venka',
    'Thera',
    'Viktoria',
    'Trine',
    'Ushara',
    'Waen',
    'Tina',
    'Violca',
    'Ulka',
    'Uzma',
    'Wen',
    'Ula',
    'Weronika',
    'Verena',
    'Yael',
    'Xue',
    'Vanda',
    'Wiola',
    'Viveka',
    'Yarden',
    'Yasuko',
    'Velma',
    'Xena',
    'Viviane',
    'Zilpha',
    'Yen',
    'Veronica',
    'Zoe',
    'Wilma',
    'Ziva',
    'Yuki',
    'Vinona',
    'Zofia',
    'Yrsa',
    'Zuleika',
    'Yuriko',
    'Vivan',
    'Adam',
    'Alain',
    'Bahram',
    'Akbar',
    'Ace',
    'Aias',
    'Alec',
    'Baraz',
    'Arun',
    'Alarico',
    'Ale',
    'Alfred',
    'Darawesh',
    'Bala',
    'Alen',
    'Andon',
    'Ancel',
    'Javed',
    'Bao',
    'Antonio',
    'Andreas',
    'Aric',
    'Gazi',
    'Bolin',
    'Aurelio',
    'Aron',
    'Arnold',
    'Merikh',
    'Chand',
    'Barry',
    'Aurel',
    'Benedikt',
    'Mithra',
    'Chao',
    'Bolivar',
    'Baltasar',
    'Bile',
    'Omid',
    'Cheng',
    'Brian',
    'Balut',
    'Bjorn',
    'Sarush',
    'Chien',
    'Caleb',
    'Barna',
    'Brian',
    'Benesh',
    'Chin-hae',
    'Carlos',
    'Beniamin',
    'Bruno',
    'David',
    'Daichi',
    'Casey',
    'Bion',
    'Cahir',
    'Fishke',
    'Darshan',
    'Chris',
    'Bohdan',
    'Charles',
    'Hershel',
    'Devjar',
    'Cole',
    'Bojan',
    'Chulainn',
    'Isaak',
    'Do-yoon',
    'Colt',
    'Borys',
    'Claus',
    'Amit',
    'Dong-hyun',
    'Damian',
    'Cezar',
    'Clay',
    'Faiz',
    'Eun-woo',
    'Dane',
    'Ciril',
    'Clyed',
    'Ahmed',
    'Fujin',
    'Denis',
    'Costia',
    'Cody',
    'Gafar',
    'Gautam',
    'Diego',
    'Cyryl',
    'Colin',
    'Hisein',
    'Goro',
    'Edward',
    'Dominik',
    'Conrad',
    'Osama',
    'Gui',
    'Eliot',
    'Doros',
    'Daniele',
    'Hadil',
    'Guozhi',
    'Eloy',
    'Drago',
    'Dante',
    'Hasan',
    'Hanuman',
    'Emerico',
    'Ediz',
    'Dominique',
    'Husain',
    'Hao',
    'Emilio',
    'Elad',
    'Donald',
    'Kamal',
    'Harish',
    'Emmet',
    'Eliasz',
    'Ebner',
    'Kitzu',
    'Haru',
    'Felix',
    'Eren',
    'Edmunt',
    'Kismat',
    'Heong-min',
    'Fernando',
    'Fadei',
    'Egill',
    'Lafit',
    'Hiroki',
    'Fidel',
    'Felicjan',
    'Emil',
    'Mahomet',
    'Hong',
    'Filipe',
    'Fred',
    'Enrico',
    'Malak',
    'Hotaka',
    'Flavio',
    'Frideric',
    'Enzo',
    'Musad',
    'Hyun',
    'Forest',
    'Fyodor',
    'Eric',
    'Melik',
    'Hyun-ki',
    'Gael',
    'Gabriel',
    'Ethan',
    'Mustafa',
    'Isao',
    'Gilbert',
    'Grigory',
    'Fabien',
    'Nagib',
    'Ji-hoon',
    'Glen',
    'Gustaw',
    'Fabio',
    'Rabi',
    'Ji-hu',
    'Goyo',
    'Haimon',
    'Fabrice',
    'Nasir',
    'Jian',
    'Gustavo',
    'Hannu',
    'Farrell',
    'Sadam',
    'Johar',
    'Hank',
    'Hektor',
    'Finn',
    'Pavel',
    'Jun',
    'Harry',
    'Henryk',
    'Franc',
    'Piotr',
    'Kailash',
    'Iago',
    'Igor',
    'Franz',
    'Rashad',
    'Kamal',
    'Ignacio',
    'Ilmari',
    'Frey',
    'Salman',
    'Kang-dae',
    'Irvine',
    'Isodor',
    'Frideric',
    'Usamah',
    'Katsuo',
    'Isandro',
    'Iwan',
    'Fritz',
    'Tariq',
    'Kazuo',
    'Jaime',
    'Jakub',
    'Garald',
    'Tahir',
    'Kenta',
    'Javier',
    'Jerzy',
    'Gino',
    'Talib',
    'Koichi',
    'Jay',
    'Joel',
    'Gotthard',
    'Zaid',
    'Kuro',
    'Jenaro',
    'Józef',
    'Gwyn',
    'Yafar',
    'Kwan',
    'Josh',
    'Juraj',
    'Hans',
    'Wasi',
    'Lang',
    'Juan',
    'Kajetan',
    'Heiden',
    'Abban',
    'Li',
    'Julio',
    'Kalman',
    'Hein',
    'Yusef',
    'Liu',
    'Kody',
    'Kazimierz',
    'Helmut',
    'Zet',
    'Mamoru',
    'Kurt',
    'Konrad',
    'Henri',
    'Samuel',
    'Maneesh',
    'Leonardo',
    'Konstantin',
    'Herman',
    'Ewaz',
    'Mani',
    'Lope',
    'Kornel',
    'Hjalmar',
    'Cairo',
    'Manju',
    'Luis',
    'Kristof',
    'Hubert',
    'Hanbal',
    'Masahiro',
    'Luke',
    'Leevi',
    'Hugo',
    'Hormaz',
    'Masaki',
    'Malcolm',
    'Lemek',
    'Ian',
    'Karim',
    'Min-jun',
    'Manuel',
    'Ludvig',
    'Ivar',
    'Darwin',
    'Mitsuo',
    'Marco',
    'Lui',
    'Jamie',
    'Kosey',
    'Nitin',
    'Markus',
    'Makariy',
    'Jason',
    'Moises',
    'Nobu',
    'Miguel',
    'Maksym',
    'Johan',
    'Amin',
    'Oda',
    'Mitch',
    'Marcin',
    'Julius',
    'Bashir',
    'Om',
    'Nash',
    'Maurycy',
    'Kai',
    'Hakim',
    'Padma',
    'Nathan',
    'Michał',
    'Kanut',
    'Iqbal',
    'Prakash',
    'Nazario',
    'Mikołaj',
    'Kathel',
    'Khaled',
    'Prem',
    'Nevil',
    'Misha',
    'Lance',
    'Mahdi',
    'Qi',
    'Nicodem',
    'Móric',
    'Lars',
    'Nabeel',
    'Quan',
    'Nicolas',
    'Nathanel',
    'Lion',
    'Qasim',
    'Rahul',
    'Octavio',
    'Nazar',
    'Lloyd',
    'Salah',
    'Raijin',
    'Oscar',
    'Nikodem',
    'Logan',
    'Suleiman',
    'Rajan',
    'Owen',
    'Odis',
    'Luca',
    'Taher',
    'Ratnam',
    'Pablo',
    'Omar',
    'Ludwig',
    'Darius',
    'Renshu',
    'Patrick',
    'Osman',
    'Magnus',
    'Shahin',
    'Ryota',
    'Paul',
    'Paion',
    'Martin',
    'Ramin',
    'Ryuu',
    'Pedro',
    'Pasha',
    'Matteo',
    'Abel',
    'Saburo',
    'Percy',
    'Perttu',
    'Max',
    'Cohem',
    'Sachin',
    'Pio',
    'Phallas',
    'Nicodem',
    'Eitan',
    'Satoshi',
    'Quin',
    'Piotr',
    'Nicolas',
    'Ezekiel',
    'Seiji',
    'Ralph',
    'Piotr',
    'Njal',
    'Hiram',
    'Seok',
    'Ramon',
    'Raphael',
    'Nudd',
    'Immanuel',
    'Shiro',
    'Raul',
    'Risto',
    'Olaf',
    'Judah',
    'Si-woo',
    'Reece',
    'Selim',
    'Olle',
    'Phineas',
    'Sung-ho',
    'Rico',
    'Serafin',
    'Ottavio',
    'Samson',
    'Sunil',
    'Ruben',
    'Sergei',
    'Otto',
    'Tobias',
    'Suresh',
    'Salvador',
    'Seth',
    'Pascal',
    'Tamir',
    'Tadao',
    'Santiago',
    'Simonce',
    'Petter',
    'Uriah',
    'Takashi',
    'Scott',
    'Szymon',
    'Philipp',
    'Uriel',
    'Takeo',
    'Sean',
    'Tius',
    'Quentin',
    'Farouk',
    'Takumi',
    'Shamus',
    'Tobiasz',
    'Raimond',
    'Gaius',
    'Taro',
    'Silva',
    'Tymon',
    'Ruben',
    'Kobe',
    'Tetsuo',
    'Terence',
    'Urho',
    'Ryan',
    'Neo',
    'Thao',
    'Thadeus',
    'Urjasz',
    'Senan',
    'Nubia',
    'U-jin',
    'Tracey',
    'Valeri',
    'Sergio',
    'Zuri',
    'Uttam',
    'Travis',
    'Vasili',
    'Seumas',
    'Serj',
    'Wei',
    'Urban',
    'Vid',
    'Simon',
    'Asad',
    'Xiang',
    'Valentin',
    'Vojtech',
    'Stefan',
    'Fadil',
    'Yamato',
    'Vince',
    'Walery',
    'Sven',
    'Khali',
    'Yang',
    'Vincent',
    'Witold',
    'Theo',
    'Sahil',
    'Yasuo',
    'Vito',
    'Yasha',
    'Tovi',
    'Ibrahim',
    'Yoshi',
    'Wade',
    'Zlatan',
    'Ulric',
    'Jamil',
    'Yuji',
    'Will',
    'Zsigmond',
    'Vilhelm',
    'Issa',
    'Zhen',
    'Zack',
]
