import { Stats } from '../../../views/CombatSim/types'

export const randomNPCs: { [key: string]: Stats } = {
    EASY: {
        movement: 4,
        currentMovement: 4,
        combat: 8,
        skills: 8,
        initiative: 5,
        armor: {
            sph: 0,
            currentSph: 0,
            spb: 4,
            currentSpb: 4,
        },
        health: 15,
        currentHealth: 15,
        weapons: { melee: { d6: 2 }, ranged: { d6: 3 } },
    },
    TYPICAL: {
        movement: 5,
        currentMovement: 5,
        combat: 10,
        skills: 10,
        initiative: 6,
        armor: {
            sph: 4,
            currentSph: 4,
            spb: 7,
            currentSpb: 7,
        },
        health: 25,
        currentHealth: 25,
        weapons: { melee: { d6: 3 }, ranged: { d6: 4 }, grenadesOrSpecialAmmo: { d4: 1 } },
    },
    DANGEROUS: {
        movement: 6,
        currentMovement: 6,
        combat: 12,
        skills: 12,
        initiative: 7,
        armor: {
            sph: 7,
            currentSph: 7,
            spb: 11,
            currentSpb: 11,
        },
        health: 35,
        currentHealth: 35,
        weapons: { melee: { d6: 4 }, ranged: { d6: 5 }, grenadesOrSpecialAmmo: { d6: 1 } },
    },
    DEADLY: {
        movement: 7,
        currentMovement: 7,
        combat: 14,
        skills: 14,
        initiative: 8,
        armor: {
            sph: 11,
            currentSph: 11,
            spb: 11,
            currentSpb: 11,
        },
        health: 55,
        currentHealth: 55,
        weapons: { melee: { d6: 5 }, ranged: { d6: 6 }, grenadesOrSpecialAmmo: { d8: 1 } },
    },
}
