import { Stats } from '../../../views/CombatSim/utils/types'

export const randomNPCs: { [key: string]: Stats } = {
    EASY: {
        isPC: false,
        ignoreSeriouslyWoundedPenalty: false,
        movement: 4,
        currentMovement: 4,
        initiative: 5,
        armor: {
            sph: 0,
            currentSph: 0,
            spb: 4,
            currentSpb: 4,
        },
        health: 15,
        currentHealth: 15,
        actions: [
            { id: 'melee', name: 'Melee', type: 'melee', value: 8, damage: { d6: 2 } },
            { id: 'ranged', name: 'Ranged', type: 'ranged', value: 8, damage: { d6: 3 } },
            { id: 'skill', name: 'Skill', type: 'skill', value: 8 },
        ],
    },
    TYPICAL: {
        isPC: false,
        ignoreSeriouslyWoundedPenalty: false,
        movement: 5,
        currentMovement: 5,
        initiative: 6,
        armor: {
            sph: 4,
            currentSph: 4,
            spb: 7,
            currentSpb: 7,
        },
        health: 25,
        currentHealth: 25,
        actions: [
            { id: 'melee', name: 'Melee', type: 'melee', value: 10, damage: { d6: 3 } },
            { id: 'ranged', name: 'Ranged', type: 'ranged', value: 10, damage: { d6: 4 } },
            { id: 'grenade', name: 'Grenade', type: 'grenade', value: 10, damage: { d6: 6 } },
            { id: 'skill', name: 'Skill', type: 'skill', value: 10 },
        ],
    },
    DANGEROUS: {
        isPC: false,
        ignoreSeriouslyWoundedPenalty: false,
        movement: 6,
        currentMovement: 6,
        initiative: 7,
        armor: {
            sph: 7,
            currentSph: 7,
            spb: 11,
            currentSpb: 11,
        },
        health: 35,
        currentHealth: 35,
        actions: [
            { id: 'melee', name: 'Melee', type: 'melee', value: 12, damage: { d6: 4 } },
            { id: 'ranged', name: 'Ranged', type: 'ranged', value: 12, damage: { d6: 5 } },
            { id: 'grenade', name: 'Grenade', type: 'grenade', value: 12, damage: { d6: 6 } },
            { id: 'skill', name: 'Skill', type: 'skill', value: 12 },
        ],
    },
    DEADLY: {
        isPC: false,
        ignoreSeriouslyWoundedPenalty: false,
        movement: 7,
        currentMovement: 7,
        initiative: 8,
        armor: {
            sph: 11,
            currentSph: 11,
            spb: 11,
            currentSpb: 11,
        },
        health: 55,
        currentHealth: 55,
        actions: [
            { id: 'melee', name: 'Melee', type: 'melee', value: 14, damage: { d6: 5 } },
            { id: 'ranged', name: 'Ranged', type: 'ranged', value: 14, damage: { d6: 6 } },
            { id: 'grenade', name: 'Grenade', type: 'grenade', value: 14, damage: { d6: 6 } },
            { id: 'skill', name: 'Skill', type: 'skill', value: 14 },
        ],
    },
}
