// Random name components
import { Style } from '../graphql/types'

export const corpoPrefixes = [
    'Arasaka',
    'Militech',
    'Biotechnica',
    'Petrochem',
    'Kang Tao',
    'Zetatech',
    'Night Corp',
    'Budget Arms',
    'Trauma Team',
    'Dynalar',
    'Orbital Air',
    'Lazarus Group',
    'Kiroshi Optics',
    'SovOil',
    'Infocomp',
    'Delamain',
    'EBM Holdings',
    'Kendachi Industries',
    'NeoNet',
    'MicroTech',
    'Nakamura Engineering',
    'WorldSat Communications',
]

export const styleAdjectives: Record<Style, string[]> = {
    [Style.AUSTERE]: ['Austere', 'Sparse', 'Minimalist', 'Plain', 'Unadorned', 'Frugal', 'Bleak', 'Simple'],
    [Style.CORPORATE]: [
        'Corporate',
        'Enterprise',
        'Executive',
        'Business',
        'Formal',
        'Streamlined',
        'Professional',
        'Regulated',
    ],
    [Style.EUROPEAN]: [
        'European',
        'Continental',
        'Classic',
        'Old-World',
        'Baroque',
        'Renaissance',
        'Colonial',
        'Mediterranean',
    ],
    [Style.EXOTIC]: ['Exotic', 'Unusual', 'Rare', 'Foreign', 'Alien', 'Mystical', 'Outlandish', 'Otherworldly'],
    [Style.LUXURIOUS]: ['Luxurious', 'Opulent', 'Lavish', 'Extravagant', 'Deluxe', 'Sumptuous', 'Gilded', 'High-End'],
    [Style.MILITARISTIC]: [
        'Militaristic',
        'Fortress',
        'Bunker',
        'Defense',
        'Tactical',
        'Armored',
        'Disciplined',
        'Regimental',
    ],
    [Style.MODERN]: [
        'Modern',
        'Contemporary',
        'Current',
        'Progressive',
        'Futuristic',
        'Cutting-Edge',
        'Sleek',
        'Techno',
    ],
    [Style.NEON_FEST]: ['Neon', 'Glow', 'Electric', 'Luminous', 'Iridescent', 'Radiant', 'Fluorescent', 'Pulsing'],
    [Style.ORIENTAL]: ['Oriental', 'Eastern', 'Zen', 'Dynasty', 'Lotus', 'Imperial', 'Silken', 'Meditative'],
    [Style.SOVIETIC]: [
        'Soviet',
        'United',
        'Red',
        'Communist',
        'Hammer-and-Sickle',
        'Proletarian',
        'People’s',
        'Industrialist',
    ],
    [Style.TRIBAL]: ['Tribal', 'Native', 'Indigenous', 'Ancestral', 'Totemic', 'Shamanic', 'Nomadic', 'Ceremonial'],
    [Style.URBAN_GRAFFITI]: ['Graffiti', 'Street', 'Urban', 'Tagged', 'Vandalized', 'Sprayed', 'Rebel', 'Concrete'],
}
