enum CharacterType {
  POLICE_LAWMAN
  TECH
  NETRUNNER_HACKER
  CORPORATE_EXEC
  AVERAGE_CITIZEN_STREETRAT
  CELEBRITY
  GOVERNMENT_OFFICIAL
  TERRORIST
  MERCENARY_FREELANCER_ASSASSIN
  NOMAD
  POP_STAR
  RELIGIOUS_FIGURE
  POLITICIAN
  RIPPERDOC
}
enum CharacterAttitude {
  WANTS_A_CREW_MEMBER_DEAD
  GENERALLY_DISLIKES_THE_CREW
  DOESN_T_TRUST_THE_CREW
  COLD_AND_PROFESSIONAL
  NEUTRAL_ATTITUDE_TOWARDS_THE_CREW
  THINKS_THE_CREW_COULD_BE_POTENTIAL_ALLIES
  TRUSTS_IN_THE_CREW_S_DECISIONS
  CONSIDERS_A_CREW_MEMBER_A_PARTNER
  CONSIDERS_A_CREW_MEMBER_A_GOOD_FRIEND
  WORSHIPS_A_CREW_MEMBER
}
