enum BountyRep {
  BRAGGER
  LOWPRO
}

enum CrimeType {
  THEFT
  MURDER
  CONTRABAND
  DRUG
  BRIBE
}

enum TheftTarget {
  POOR_SOUL
  VENDIT
  OASIS
  PUBLIC_ELEMENT
  MINI_CORP
  MEGA_CORP
}

enum MurderTarget {
  GANGER
  CITIZEN
  CORPO
  COP
  EXEC
  POLITICIAN
}

enum ContrabandTarget {
  COSTLY
  PREMIUM
  EXPENSIVE
  VERY_EXPENSIVE
  LUXURY
  SUPER_LUXURY
}

enum DrugTarget {
  SMASH
  STIM
  BLUE_GLASS
  SYNTHCOKE
  BOOST
  BLACK_LACE
}

enum BribeTarget {
  GANGER
  CITIZEN
  CORPO
  COP
  EXEC
  POLITICIAN
}

enum BountyStatus {
  ACTIVE
  CAPTURED
  DEAD
}
