enum BuildingType {
    ABANDONED_BUILDING
    VACANT_LOT_CONSTRUCTION_SITE
    CUBE_HOTEL_MOTEL_CARGO_CONTAINER
    PUBLIC_SPACE
    ESTABLISHMENT
    MULTI_STORY_BUILDING
    SKYSCRAPER_MEGABUILDING
    COMMERCIAL_BUILDING
    CORPO_BUILDING
    LUXURY_PENTHOUSE_MCMANSION
    GOV_BUILDING
    MEGACORPO_HQ
}

enum Ownership {
    NO_ONE_SCAVS
    LOW_LEVEL_GONKS
    GANG_MAFIA
    POSERGANG
    BYSTANDER
    FIXER
    LOCAL_GOV
    SMALL_BUSINESS
    CORPO
    MILITARISTIC_GANG
    GOVERNMENT
    MEGA_CORPO
}

enum SecurityPersonnel {
    NONE
    LOCALS_TENNANTS
    LOCAL_SEC_GANG
    VEHICLES
    CITY_SEC
    CORPO_SEC
    RESPONSE_BACKUP
    HEAVY_WEAPONS
    HEAVY_VEHICLES
    FAST_RESPONSE_BACKUP
    ELITE_TROOPS
    BORG
}

enum Style {
    AUSTERE
    SOVIETIC
    URBAN_GRAFFITI
    MODERN
    TRIBAL
    NEON_FEST
    EUROPEAN
    MILITARISTIC
    CORPORATE
    ORIENTAL
    EXOTIC
    LUXURIOUS
}

enum Event {
    CRUMBLING_DEMOLITION
    WORKERS_REMODELING
    MAINTENANCE_PROBLEM
    STRIKE
    PRIVATE_INVESTIGATOR
    ONGOING_KIDNAP
    NETRUNNER_MESSING_WITH_SYSTEMS
    GUN_FIGHT
    OWNERS_COLLECTING_RENT
    EDGERUNNERS_GOING_SAME_PLACE
    STRONG_SECURITY_PRESENCE
    ELITE_CREW_VISITING
}

enum Secret {
    PARTY
    DRUG_STASH
    FIXER_ARRANGEMENT
    DRUG_LAB
    SOMEONE_KIDNAPPED
    WEAPON_STASH
    DATA_STORE_NETRUNNER_DEN
    MEDIA_INVESTIGATION
    ACTIVIST_SABOTAGE
    SAFE_HOUSE
    COVERT_OP_MEETING_POINT
    SECRET_SCIENCE_LAB
}
