use std::fs;
use std::io::Write;
use std::path::Path;
use flate2::read::GzDecoder;
use tar::Archive;

fn main() {
    // Generate embedded cloudflared binary
    generate_embedded_cloudflared();

    // Download cloudflared binaries for different platforms (for development)
    download_cloudflared_binaries();

    tauri_build::build()
}

fn generate_embedded_cloudflared() {
    let bin_dir = Path::new("../bin");
    fs::create_dir_all(&bin_dir).expect("Failed to create bin directory");

    // Get the target triple from Cargo's TARGET environment variable
    // This is the actual target we're building for, not the host OS
    let target = std::env::var("TARGET").expect("TARGET environment variable not set");
    
    // Determine the platform based on the target triple
    let (download_name, is_tgz, binary_name, target_triple) = if target.contains("windows") {
        ("cloudflared-windows-amd64.exe", false, "cloudflared.exe", "x86_64-pc-windows-msvc.exe")
    } else if target.contains("apple-darwin") || target.contains("macos") {
        ("cloudflared-darwin-amd64.tgz", true, "cloudflared", "x86_64-apple-darwin")
    } else if target.contains("linux") {
        ("cloudflared-linux-amd64", false, "cloudflared", "x86_64-unknown-linux-gnu")
    } else {
        panic!("Unsupported target platform: {}", target);
    };

    let target_path = bin_dir.join(format!("cloudflared-{}", target_triple));
    let embedded_rs_path = Path::new("src/embedded_cloudflared.rs");

    // Download if not exists
    if !target_path.exists() {
        let url = format!(
            "https://github.com/cloudflare/cloudflared/releases/latest/download/{}",
            download_name
        );

        println!("cargo:warning=Downloading {} to {}", url, target_path.display());

        // Download the file using reqwest (blocking)
        let response = reqwest::blocking::get(&url)
            .expect(&format!("Failed to download cloudflared from {}", url));
        
        if !response.status().is_success() {
            panic!("Failed to download {}: HTTP {}", download_name, response.status());
        }

        // Download and process the file
        if is_tgz {
            // For macOS, download and extract the tar.gz
            let temp_path = bin_dir.join("temp.tgz");
            let mut file = fs::File::create(&temp_path)
                .expect("Failed to create temp file");
            let content = response.bytes().expect("Failed to read response body");
            file.write_all(&content)
                .expect("Failed to write downloaded file");

            // Extract the tar.gz using flate2 and tar crates
            let tar_gz = fs::File::open(&temp_path)
                .expect("Failed to open downloaded tar.gz");
            let tar = GzDecoder::new(tar_gz);
            let mut archive = Archive::new(tar);
            
            let temp_dir = bin_dir.join("temp");
            fs::create_dir_all(&temp_dir).expect("Failed to create temp directory");
            
            archive.unpack(&temp_dir)
                .expect("Failed to extract tar.gz");

            // Move the extracted binary
            let extracted_path = temp_dir.join("cloudflared");
            if !extracted_path.exists() {
                panic!("Extracted binary not found at {}", extracted_path.display());
            }
            fs::rename(&extracted_path, &target_path)
                .expect("Failed to move extracted binary");

            // Clean up
            fs::remove_file(&temp_path).ok();
            fs::remove_dir_all(&temp_dir).ok();
        } else {
            // For Windows and Linux, download directly
            let mut file = fs::File::create(&target_path)
                .expect("Failed to create target file");
            let content = response.bytes().expect("Failed to read response body");
            file.write_all(&content)
                .expect("Failed to write downloaded file");
        };

        // Make executable on Unix systems
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = fs::metadata(&target_path).unwrap().permissions();
            perms.set_mode(0o755);
            fs::set_permissions(&target_path, perms).unwrap();
        }
    }

    // Generate embedded Rust source using include_bytes! for better memory efficiency
    let mut rs_content = String::new();

    rs_content.push_str(&format!("// Auto-generated file containing embedded cloudflared binary for {}\n", target_triple));
    rs_content.push_str("// This file is generated by build.rs - do not edit manually\n\n");
    
    // Use include_bytes! macro which is more memory-efficient than embedding as a static array
    // The binary path is relative to the src directory
    let binary_path_relative = format!("../bin/cloudflared-{}", target_triple);
    rs_content.push_str(&format!("pub static CLOUDFLARED_BINARY: &[u8] = include_bytes!(\"{}\");\n\n", binary_path_relative));

    rs_content.push_str(&format!("pub const CLOUDFLARED_BINARY_NAME: &str = \"{}\";\n", binary_name));

    fs::write(&embedded_rs_path, rs_content).expect("Failed to write embedded cloudflared source");

    // Tell cargo to rebuild if the binary changes
    println!("cargo:rerun-if-changed={}", target_path.display());
}

fn download_cloudflared_binaries() {
    let bin_dir = Path::new("../bin");
    fs::create_dir_all(&bin_dir).expect("Failed to create bin directory");

    // Get the target triple from Cargo's TARGET environment variable
    let target = std::env::var("TARGET").expect("TARGET environment variable not set");
    
    // Determine the platform based on the target triple
    let (download_name, is_tgz, target_triple) = if target.contains("windows") {
        ("cloudflared-windows-amd64.exe", false, "x86_64-pc-windows-msvc.exe")
    } else if target.contains("apple-darwin") || target.contains("macos") {
        ("cloudflared-darwin-amd64.tgz", true, "x86_64-apple-darwin")
    } else if target.contains("linux") {
        ("cloudflared-linux-amd64", false, "x86_64-unknown-linux-gnu")
    } else {
        panic!("Unsupported target platform: {}", target);
    };

    let target_path = bin_dir.join(format!("cloudflared-{}", target_triple));

    // Skip if already exists
    if target_path.exists() {
        println!("cargo:warning={} already exists, skipping download", target_path.display());
        return;
    }

    let url = format!(
        "https://github.com/cloudflare/cloudflared/releases/latest/download/{}",
        download_name
    );

    println!("cargo:warning=Downloading {} to {}", url, target_path.display());

    // Download the file using reqwest (blocking)
    let response = reqwest::blocking::get(&url)
        .expect(&format!("Failed to download cloudflared from {}", url));
    
    if !response.status().is_success() {
        panic!("Failed to download {}: HTTP {}", download_name, response.status());
    }

    // Download and process the file
    if is_tgz {
        // For macOS, download and extract the tar.gz
        let temp_path = bin_dir.join("temp.tgz");
        let mut file = fs::File::create(&temp_path)
            .expect("Failed to create temp file");
        let content = response.bytes().expect("Failed to read response body");
        file.write_all(&content)
            .expect("Failed to write downloaded file");

        // Extract the tar.gz using flate2 and tar crates
        let tar_gz = fs::File::open(&temp_path)
            .expect("Failed to open downloaded tar.gz");
        let tar = GzDecoder::new(tar_gz);
        let mut archive = Archive::new(tar);
        
        let temp_dir = bin_dir.join("temp");
        fs::create_dir_all(&temp_dir).expect("Failed to create temp directory");
        
        archive.unpack(&temp_dir)
            .expect("Failed to extract tar.gz");

        // Move the extracted binary
        let extracted_path = temp_dir.join("cloudflared");
        if !extracted_path.exists() {
            panic!("Extracted binary not found at {}", extracted_path.display());
        }
        fs::rename(&extracted_path, &target_path)
            .expect("Failed to move extracted binary");

        // Clean up
        fs::remove_file(&temp_path).ok();
        fs::remove_dir_all(&temp_dir).ok();
    } else {
        // For Windows and Linux, download directly
        let mut file = fs::File::create(&target_path)
            .expect("Failed to create target file");
        let content = response.bytes().expect("Failed to read response body");
        file.write_all(&content)
            .expect("Failed to write downloaded file");
    };

    // Make executable on Unix systems
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&target_path).unwrap().permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&target_path, perms).unwrap();
    }

    println!("cargo:warning=Downloaded and prepared {}", target_path.display());
}
