# PLOT
enum PlotCharacterVerb {
  KILL
  ESCORT
  ROB
  RESCUE
  INTIMIDATE
  INTERROGATE
  INVESTIGATE
  RECRUIT
}
enum PlotItemVerb {
  STEAL
  DELIVER
  MODIFY
  DESTROY
  USE
  TRADE
  HIDE
}
enum PlotGangVerb {
  INFILTRATE
  ALLY_WITH
  NEGOTIATE_WITH
  CHALLENGE
  SABOTAGE
  INVESTIGATE
}
enum PlotBuildingVerb {
  INVESTIGATE
  OCCUPY
  DEFEND
  LOOT
  VANDALIZE
}
# PLOT COMPLICATIONS
enum PlotComplicationType {
  CHARACTER_HUNTING_CREW # CHARACTER
  THEY_KNOW_THE_CREW_IS_COMING # ITEM
  HEAVY_WELL_ARMED_SECURITY_FOR_ITEM # ITEM
  THE_CREW_IS_ON_THEIR_OWN
  AREA_IS_PATROLLED_BY_POLICE
  AREA_IS_A_COMMON_DRUG_SALE_ZONE
  THE_CREW_DOESN_T_GET_PAID_STIFFED
  AREA_SUFFERS_A_POWER_OUTAGE
  FLASH_FLOOD_HEAVY_RAIN_HEAVY_FOG
  INNOCENT_BYSTANDERS
}

# CHARACTER
enum PlotCharacterType {
  POLICE_LAWMAN
  TECH
  NETRUNNER_HACKER
  CORPORATE_EXEC
  AVERAGE_CITIZEN_STREETRAT
  CELEBRITY
  GOVERNMENT_OFFICIAL
  KNOWN_TERRORIST
  MERCENARY_FREELANCER_ASSASSIN
  NOMAD
  POP_STAR
  RELIGIOUS_FIGURE
  POLITICIAN
  RIPPERDOC
}
enum PlotCharacterAttitude {
  WANTS_A_CREW_MEMBER_DEAD
  GENERALLY_DISLIKES_THE_CREW
  DOESN_T_TRUST_THE_CREW
  COLD_AND_PROFESSIONAL
  NEUTRAL_ATTITUDE_TOWARDS_THE_CREW
  THINKS_THE_CREW_COULD_BE_POTENTIAL_ALLIES
  TRUSTS_IN_THE_CREW_S_DECISIONS
  CONSIDERS_A_CREW_MEMBER_A_PARTNER
  CONSIDERS_A_CREW_MEMBER_A_GOOD_FRIEND
  WORSHIPS_A_CREW_MEMBER
}

# ITEM
enum PlotItemType {
  MONEY
  WEAPONS
  BIOLOGICAL_SAMPLES
  DRUGS_ILLEGAL_CONTRABAND
  CYBERWARE
  DIGITAL_FILES
  FOOD_FUELS_SUPPLIES
  VEHICLE
  EXOTIC_ANIMAL
  AI_ROBOT_DRONE
}
enum PlotItemCondition {
  BROKEN_AND_IN_PIECES
  LOW_GRADE_CHEAP_MATERIALS
  FUNCTIONAL_AND_UTILITARIAN
  BELOW_AVERAGE_QUALITY
  AVERAGE_QUALITY
  GOOD_CONDITION_BUT_USED
  BRAND_NEW_AND_IN_GREAT_CONDITION
  ENHANCED_IN_SOME_WAY_AND_SOUGHT_AFTER
  COLLECTORS_ITEM_FEW_IN_EXISTENCE
  ONE_OF_A_KIND_ITEM_TOP_QUALITY
}

# GANG
# There is no PlotGangType because it is a Gang
enum PlotGangComplicationType {
  LEADER_IS_CHARACTER # CHARACTER
  RECENTLY_LOST_CONTROL
  SPLIT_OVER_IDEOLOGY_PUSHED_BY_CHARACTER # CHARACTER
  RUNNING_SMUGGLING_FOR_ITEM # ITEM
  BLACKMAILED_BY_CHARACTER # CHARACTER
  REVERES_AI_CONTAINED_IN_ITEM_AS_RELIGIOUS_SYMBOL # ITEM
  BUILT_AROUND_CHARACTER # CHARACTER
  BEING_SABOTAGED_BY_CHARACTER # CHARACTER
  POLICE_RAIDING
}

# BUILDING COMPLICATIONS
# There is no PlotBuildingType because it is a Building
enum PlotBuildingComplicationType {
  TRAUMA_TEAM_ON_THE_SCENE
  NEED_ID_PASSWORD_TO_GET_IN_HELD_BY_CHARACTER # CHARACTER
  HEAVY_TRAFFIC
  RECENTLY_TAGGED_AND_LOOTED
  FORTIFIED_POSITIONS_BY_SECURITY_PERSONNEL_BECAUSE_OF_ITEM # ITEM
  NO_GUN_ZONE
  SHOOTOUT_WITH_POLICE_AND_CYBERPSYCHO_CHARACTER # CHARACTER
  CCTV_POLICE_SURVEILLANCE_IS_HEAVY
  CONCERT_HOSTED_BY_CHARACTER # CHARACTER
  ACCIDENT_ZONE_INVOLVES_SHIPMENT_OF_ITEM # ITEM
}

# JOB DIFFICULTY
enum JobDifficulty {
  EASY
  TYPICAL
  DANGEROUS
}
