# To allow a union of different verb types, wrap each enum value in a separate object type.
interface Verb {
  value: String!
}
# Wrapper for CharacterVerb enum values.
type CharacterVerbWrapper implements Verb {
  value: CharacterVerb!
}
# Wrapper for ItemVerb enum values.
type ItemVerbWrapper implements Verb {
  value: ItemVerb!
}
# Wrapper for PlotGangVerb enum values.
type PlotGangVerbWrapper implements Verb {
  value: PlotGangVerb!
}
# Wrapper for PlotBuildingVerb enum values.
type PlotBuildingVerbWrapper implements Verb {
  value: PlotBuildingVerb!
}
# The PlotVerb union aggregates all verb wrapper types.
union PlotVerb =
    CharacterVerbWrapper
  | ItemVerbWrapper
  | PlotGangVerbWrapper
  | PlotBuildingVerbWrapper

# The FixerJob type represents a job or mission within the narrative.
type FixerJob {
  ID: ID!
  name: String!
  description: String!
  plot: Plot!
  image: String!
  difficulty: JobDifficulty!
}

# The Plot type represents the overall plot of a FixerJob.
type Plot {
  # The verb indicates the main action to take.
  verb: PlotVerb!
  # plotBuilding represents the building where the plot takes place.
  plotBuilding: PlotBuilding!
  # If the focus is not on the building, plotSubject will represent either a character, an item, or a gang.
  plotSubject: PlotSubject
  # Complication describes what complicates the plot.
  plotComplication: PlotComplication!
}

# The PlotSubject union represents the possible subjects of the plot.
union PlotSubject = Character | Item | PlotGang

# The PlotGang type represents a gang involved in the plot.
type PlotGang {
  gang: Gang!
  complication: GangComplication!
}

# The PlotBuilding type represents a building where the plot occurs.
type PlotBuilding {
  building: Building!
  complication: BuildingComplication!
}

# The PlotComplication type describes an obstacle or complication in the plot.
type PlotComplication {
  type: PlotComplicationType!
  # The following fields are conditionally set based on the complication type.
  character: Character
  item: Item
}

# GangComplication gives details about complications involving a gang.
type GangComplication {
  type: PlotGangComplicationType!
  # The following fields are conditionally set based on the complication type.
  character: Character
  item: Item
}

# BuildingComplication gives details about complications involving the plot building.
type BuildingComplication {
  type: PlotBuildingComplicationType!
  # The following fields are conditionally set based on the complication type.
  character: Character
  item: Item
}
